### ISSUE TITLE
Spaces in comment rendered as exclamation point

### ISSUE THREAD

**Issue by trishume** [makepad/makepad#1]
Steps to reproduce:
- Go to https://makepad.github.io/makepad/ on latest "selection" commit
- Scroll down to see comment
- Spaces in comments are rendered as `!` until they are selected then they're rendered as bullets

**Comment by makepaddev** [comment]
Oopsie. thx for telling me. I'm liveposting updates so its not really useful to open issues just yet. A tweetreply will do for now!
