### ISSUE TITLE
The editor won't update the status of command key after re-focused.

### ISSUE THREAD

**Issue by chengluyu** [makepad/makepad#10]
Step to reproduce:
1. Focus the editor
2. Hold command key, the editor will enter multi-cursor mode.
3. Keep holding and switch to another tab in your browser
4. Switch back to the editor without holding command key
5. Multi-cursor is still enabled before you press command key again 

Screen record (notice the key caster)
![2019-07-09 21 39 43](https://user-images.githubusercontent.com/2239547/60892710-2cad7180-a292-11e9-845e-fe7ca8fd1812.gif)

**Comment by chengluyu** [comment]
Forget to mention:
* Browser: Google Chrome 75.0.3770.90 (stable)
* OS: macOS Catalina 19A501i

~I will try it on stable version of macOS and Windows later.~

Update 1: Cannot reproduce on 75.0.3770.100 (stable) on Windows 10.
Update 2: Reproducible on 75.0.3770.100 (stable) on macOS Mojave (18F132, the latest version of stable macOS).

**Comment by makepaddev** [comment]
Thanks for the report, i'll see why it does that. I thought i did a key-up on all focus lost but maybe tab switch is different.

**Comment by makepaddev** [comment]
Fixed in dev. Should go to master soon.
