### ISSUE TITLE
Newsletter subscription seems broken

### ISSUE THREAD

**Issue by jryans** [makepad/makepad#109]
👋 Hi friends! 😄 

I tried to use the newsletter subscription button on "Edit" tab, but it seems to cause a 500 error:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/279572/107572472-3fadc380-6be4-11eb-9c49-a7e964cabf22.png">

Keep up the good work, seems like a very interesting project! 😊

**Comment by makepaddev** [comment]
Is replaced soon.
