### ISSUE TITLE
when trying to build on osx apple silicon

### ISSUE THREAD

**Issue by gschian0** [makepad/makepad#111]
gennaroschiano@Gennaros-MacBook-Pro makepad % cargo run -p makepad --release
    Finished release [optimized] target(s) in 0.01s
     Running `target/release/makepad`
error: package ID specification `webgl_example_wasm` matched no packages

... would love to get this running!

**Comment by makepaddev** [comment]
This is just a warning about the project, it should start up fine otherwise though? Can't you see the editor?

**Comment by makepaddev** [comment]
Also try rm *.ron in the makepad root, maybe its a leftover from a previous attempt.

**Comment by gschian0** [comment]
I tried rm *.ron and same result... I the terminal just hangs up and no editor opens.

**Comment by gschian0** [comment]
if I open the index.html file is says "makepad is loading" indefinitely
