### ISSUE TITLE
Three crates for each application is unnecessary

### ISSUE THREAD

**Issue by janpaul123** [makepad/makepad#116]
Currently there are 3 versions of each app:
* [The one that gets run with `cargo run`](https://github.com/makepad/makepad/blob/master/examples/bare_example/Cargo.toml)
* [The one that gets compiled with `cargo build --target=wasm32-unknown-unknown`](https://github.com/makepad/makepad/blob/fc88156e4f6577e71c5fa76eb95873ebd81b9865/examples/bare_example/wasm/Cargo.toml)
* [The app itself](https://github.com/makepad/makepad/blob/fc88156e4f6577e71c5fa76eb95873ebd81b9865/examples/bare_example/app/Cargo.toml)

Rik explained that this is done because wasm needs `crate-type = ["cdylib"]`, which is [currently not dynamically configurable](https://github.com/rust-lang/cargo/issues/4881).

However, wasm doesn't _really_ need to be a `cdylib`. If you don't set that you just get a tiny extra `start` function, which we can just ignore. This adds a few kb at most, or less than 0.1% in both release and debug builds (in my testing) — I'm not even sure why it's that much instead of a few bytes.. Anyway, if you really care about that amount, it can easily be stripped after the fact (e.g using [wasm-snip](https://github.com/rustwasm/wasm-snip)).

I think this is worth it for simplifying the crate structure for newcomers. We can then just have one top-level `main_app` macro:

```rust
#[macro_export]
macro_rules!main_app {
    ( $ app: ident) => {
        #[cfg(not(target_arch = "wasm32"))]
        fn main(){
            //TODO do this with a macro to generate both entrypoints for App and Cx
            let mut cx = Cx::default();
            cx.style();
            $ app::style(&mut cx);
            cx.init_live_styles();
            let mut app = $ app::new(&mut cx);
            let mut cxafterdraw = CxAfterDraw::new(&mut cx);
            cx.event_loop( | cx, mut event | {
                if let Event::Draw = event {
                    app.draw_app(cx);
                    cxafterdraw.after_draw(cx);
                    return
                }
                app.handle_app(cx, &mut event);
            });
        }

        #[cfg(target_arch = "wasm32")]
        fn main() {}

        #[cfg(target_arch = "wasm32")]
        #[export_name = "create_wasm_app"]
        pub extern "C" fn create_wasm_app() -> u32 {
            std::panic::set_hook(Box::new(|info: &std::panic::PanicInfo| {
                log!("Panic: {}", info.to_string());
            }));
            let mut cx = Box::new(Cx::default());
            cx.style();
            $ app::style(&mut cx);
            cx.init_live_styles();
            let app = Box::new( $ app::new(&mut cx));
            let cxafterdraw = Box::new(CxAfterDraw::new(&mut cx));
            Box::into_raw(Box::new((Box::into_raw(app), Box::into_raw(cx), Box::into_raw(cxafterdraw)))) as u32
        }

        #[cfg(target_arch = "wasm32")]
        #[export_name = "process_to_wasm"]
        pub unsafe extern "C" fn process_to_wasm(appcx: u32, msg_bytes: u32) -> u32 {
            let appcx = &*(appcx as *mut (*mut $ app, *mut Cx, *mut CxAfterDraw));
            (*appcx.1).process_to_wasm(msg_bytes, | cx, mut event | {
                if let Event::Draw = event {
                    (*appcx.0).draw_app(cx);
                    (*appcx.2).after_draw(cx);
                    return;
                };
                (*appcx.0).handle_app(cx, &mut event);
            })
        }
    }
}
```

**Comment by makepaddev** [comment]
Fixed!
