### ISSUE TITLE
mace segfaults on post_signal

### ISSUE THREAD

**Issue by redmar** [makepad/makepad#119]
Heya, following this project with a lot of enthusiasm, very eager to see first releases of your pivot to the UI designer 😃 .

I tried running mace on an M1 Macbook Air (under MacOS) but it segfaults consistently for me, I can trace it back to cx_cocoa and the post_signal calls within mace app.rs, it seems they are 'faster' calling post_signal within their thread::spawn than the CocoaApp::init can run, so it has a zero pointer in CxCocoa post_signal fn. (when i add a couple of millis sleep before those mace app.rs post_signal calls then everything works fine.)

I don't mind trying to write a PR for it but I'm not sure about the solution direction in this case. Should the post_signals calls be buffered before the init? or just drop them when the global CxCocoaApp init() is not called yet?

Are you peeps on a public channel/discord e.g. somewhere to ask/discuss these? (i'm also fine to do it here)

ps. saw Rik last time presenting makepad at the technolution gouda rust meetup, another meetup previewing the 'new' makepad anytime soon? :-)

**Comment by makepaddev** [comment]
Hi! Yea we believe the UI designer is the key to value for the entire stack so. Going to keep going untill that fully works. So eddy is making mace, and he apparently put a startup race condition into it. I'll tell him, or maybe we need to change our own startup flow a bit. Thanks for the report. Indeed just pugging a small delay in there is a 'fix' however i'd rather make sure you cant post before we have a cocoa app object entirely.

**Comment by makepaddev** [comment]
How do i send you a PM with the discord invite link?

**Comment by makepaddev** [comment]
Found you on twitter.
