### ISSUE TITLE
Using freed memory in xlib.rs

### ISSUE THREAD

**Issue by emoon** [makepad/makepad#123]
Hi,

I have noticed some problematic code here (and may be in a few more places)

https://github.com/makepad/makepad/blob/dev/render/src/platform/linux/xlib.rs#L116-L129

The problem with this statement: `CString::new("CLIPBOARD").unwrap().as_ptr()`

is that `.as_ptr()` will take the address of a freed pointer that was constructed o the heap, with latest nightly compiler one now gets a warning like this

```
125 |                 atom_targets: X11_sys::XInternAtom(display, CString::new("TARGETS").unwrap().as_ptr(), 0),
    |                                                             -------------------------------- ^^^^^^ this pointer will be invalid
    |                                                             |
    |                                                             this `CString` is deallocated at the end of the statement, bind it to a variable to extend its lifetime
    |
    = note: pointers do not have a lifetime; when calling `as_ptr` the `CString` will be deallocated at the end of the statement because nothing is referencing it as far as the type system is concerned
    = help: for more information, see https://doc.rust-lang.org/reference/destructors.html
```

In cases like this there is no need to construct a heap-based string and pass it down to the C API. It's possible to just do `b"TARGETS\0"` (or use `CStr`)

**Comment by makepaddev** [comment]
Hi! Thanks for the report, these are definitely areas we screw up. Right now our development tree has left linux/windows behind for a while (otherwise im going insane) so once we pick that up again we'll review these areas.

**Comment by makepaddev** [comment]
The gap between 'master' and 'dev' in terms of systems is almost a year and a half and comprises almost an entire rewrite.  So if yr looking into what we do 'master' is not all that exciting. Esp the shader compiler / live coding has leveled up significantly. General ideas hold tho.

**Comment by makepaddev** [comment]
In that sense i see you link to 'dev' so you won't be able to compile for a while on linux. I have to do quite a bit of work on the render stack and shader GLSL generator to get it back up.

**Comment by emoon** [comment]
Yeah I was building master first (dev doesn't build for me on Linux) so I just took a look at the dev-tree instead and the link above to code in `dev` so I figured the issue may still be around on the dev branch.

**Comment by makepaddev** [comment]
Yep its on the todolist now. Thanks

**Comment by makepaddev** [comment]
I'm finally processing your suggestion as we are fixing up linux again :)
