### ISSUE TITLE
can't build on macOS

### ISSUE THREAD

**Issue by wtholliday** [makepad/makepad#135]
I'm doing `cargo run -p makepad --release` and I get:

```
error: no matching package named `makepad-render` found
location searched: https://github.com/makepad/makepad.git?branch=dev
required by package `makepad-code-editor v0.1.0 (/Users/holliday/makepad/codeeditor)`
```

macOS 12.2 (21D49), rustc 1.58.1 (db9d1b20b 2022-01-20), cargo 1.58.0 (f01b232bc 2022-01-19)

**Comment by makepaddev** [comment]
Hi sorry i should update the readme. Dev and live are already on our new track. So you run cargo run -p makepad_studio however its all very new and not very stable. If you are on master it should still work

**Comment by makepaddev** [comment]
Should be fixed now on master
