### ISSUE TITLE
Linux install is kinda broken

### ISSUE THREAD

**Issue by J3fflo** [makepad/makepad#137]
Linux != Ubuntu / Debia
Not all linux distros use apt package manager, thus, you shouldnt use apt in the linux_rustup.sh,
just add libxcursor-dev libx11-dev libgl1-mesa-dev under dependencies and let the users install them, or make a check, but as mentioned, there are a lot of package managers... soo a lot of cases.

**Comment by makepaddev** [comment]
Fair enough, when we get back to making linux work (the main branch is >1.5 years old by now) i'll rename it to debian_rustup.sh

**Comment by makepaddev** [comment]
We're replacing all these scripts with a new build-tool where this will be updated
