### ISSUE TITLE
Opening .ttf files crashes in studio

### ISSUE THREAD

**Issue by joepio** [makepad/makepad#141]
- Open makepad_studio (on an m1 mac) `cargo +nightly-2022-07-09 run -p makepad_studio --release`
- Navigate to `/resources/`, open any `.ttf` file

```
thread 'main' panicked at 'index out of bounds: the len is 64258 but the index is 65533', platform/src/draw_2d/draw_text.rs:254:28
```

**Comment by makepaddev** [comment]
Then don't click those ;). We're working on the IDE part to behave normally :)
