### ISSUE TITLE
Different clipboards for different cursors in multicursor mode

### ISSUE THREAD

**Issue by Theocrat** [makepad/makepad#150]
In most code editors which support multi-cursor mode, each distinct cursor tends to have its own clipboard. This allows a user to create X cursors (where X is some number), use them to select X words on different lines, copy them with Ctrl+C, and then move these X cursors to X new positions and then hit Ctrl+V to paste the X distinct copied values neatly into each of the X new positions.

On the other hand, in Lapce (as it stands today), copying with multi-cursor doesn't work this way. It adds X lines worth of text into the clipboard, and Ctrl+V pastes all the X lines into each of the X cursor positions thereafter. This causes a veritable explosion of text in the editor and everything is thrown aside and scattered asunder.

I am requesting the kind of multi-cursor clipboard that VSCode and Atom have. I would have done it myself, but (1) I am kinda busy these days and (2) I am an utter noob in Rust (I find it harder than C). Nevertheless, if it is absolutely not possible for anyone to find time to work on this feature, I will still be grateful if someone can point me to the portion of the code which handles copying and other actions under multi-cursor. Then I can give it a shot and see if I can build a pull request.

(Don't count on it though. Once again, I am at that point of Rust learning where I find Rust harder than C)

**Comment by makepaddev** [comment]
Hi, thanks for your comment here.
I agree having multiple clipboard for multicursor is a nice feature to have. Since we're rewriting the editor i'll make note of it to include it in the design.
