### ISSUE TITLE
I can't open  https://127.0.0.1:8080/makepad/examples/ironfish/src/index.html

### ISSUE THREAD

**Issue by liangfz-kit** [makepad/makepad#152]
liangfangzheng@liangfzmac makepad % `cargo run -p makepad-web-server --release`
    Finished release [optimized] target(s) in 0.03s
     Running `target/release/makepad-web-server`
Server listening on 127.0.0.1:8080

but i can't open https://127.0.0.1:8080/makepad/examples/ironfish/src/index.html

**Comment by makepaddev** [comment]
Hi so, the server is http NOT https (see your url). Also you do still need to compile the wasm file. Just running the webserver won't do that.

**Comment by makepaddev** [comment]
I am working on a new way to build and serve wasm files to make all this easier tho. But it does work.
