### ISSUE TITLE
Error writing file ./edit_repo/makepad_state.json

### ISSUE THREAD

**Issue by MarcoPolo** [makepad/makepad#16]
MacOS 10.14, after running ./run_first_init.sh, and then cargo run.

I see Makepad running! It prompts me to hit F9. When I do, I get the error writing file and a blank other makepad (If i try to type anything in the new window it crashes/closes).

Is this suppose to happen? or what is? Thanks, this is awesome!
<img width="328" alt="Screen Shot 2019-08-09 at 4 11 45 PM" src="https://user-images.githubusercontent.com/594035/62813701-17aa4500-bac1-11e9-8183-ce158fc4b1fc.png">

```
$ ls -lha edit_repo/makepad_state.json
-rw-r--r--  1 marco  staff   1.0K Aug  9 16:13 edit_repo/makepad_state.json
```

makepad_state.json:
```
{"windows":[{"window_position":{"x":804.0,"y":384.0},"window_inner_size":{"x":865.0,"y":1135.0},"dock_items":{"Splitter":{"align":"First","pos":150.0,"axis":"Vertical","first":{"TabControl":{"current":0,"tabs":[{"closeable":false,"title":"Files","item":"FileTree"}]}},"last":{"Splitter":{"align":"Last","pos":150.0,"axis":"Horizontal","first":{"TabControl":{"current":4,"tabs":[{"closeable":false,"title":"Edit","item":"FileEditorTarget"},{"closeable":true,"title":"main.rs","item":{"FileEditor":{"path":"examples/quad/src/main.rs","editor_id":1}}},{"closeable":true,"title":"cx_cocoa.rs","item":{"FileEditor":{"path":"render/src/cx_cocoa.rs","editor_id":2}}},{"closeable":true,"title":"cx_fonts.rs","item":{"FileEditor":{"path":"render/src/cx_fonts.rs","editor_id":3}}},{"closeable":true,"title":"cx_opengl.rs","item":{"FileEditor":{"path":"render/src/cx_opengl.rs","editor_id":4}}}]}},"last":{"TabControl":{"current":0,"tabs":[{"closeable":false,"title":"Rust Compiler","item":"RustCompiler"},{"closeable":false,"title":"Keyboard","item":"Keyboard"}]}}}}}}}]}
```

**Comment by MarcoPolo** [comment]
Oh, duh. the error is from the editor inside the `edit_repo`. It's complaining that it doesn't know about `edit_repo/edit_repo`. Nothing to see here.

**Comment by makepaddev** [comment]
Yep thats recursion :) If you want the editor yr editing to have something to edit you need to check out another edit_repo :)

**Comment by makepaddev** [comment]
I'm currently working on the actual application again, so it will get proper project support and drag/drop folders onto the UI and stuff like that. For now its hardcoded to dogfood, which is what i use it for.
