### ISSUE TITLE
Current branch?

### ISSUE THREAD

**Issue by rvanlaar** [makepad/makepad#162]
Hi,

I'm looking into using makepad.
What is the recommended branch to use?

Hopefully Linux support is nearly there.

Ps. The discord invite link from the readme is invalid. Do you have a new one?

**Comment by jason-yau** [comment]
Branch: [rik](https://github.com/makepad/makepad/tree/rik)
Discord: https://discord.gg/adqBRq7Ece

**Comment by makepaddev** [comment]
Yea even though that branch is my personal 'might be broken at anytime' work branch it is the current leading branch. We're going to push to master probably in 1-2weeks so this is less of the case. But i did build linux / windows / everything platform support into it.

**Comment by rvanlaar** [comment]
Thanks, will check it out.

**Comment by rvanlaar** [comment]
Note: had to install rustup from rustup.rs.

The rustup version on Ubuntu was very old.
