### ISSUE TITLE
Can not enter or display Japanese, Korean, Chinese, Emoji ....

### ISSUE THREAD

**Issue by greggman** [makepad/makepad#179]
I'm guessing that's intentional but if not, you might find these articles interesting on why rendering text for a text editor is harder than it looks and text input is also harder than it looks and why you should probably consider looking for a way to base the text editing (as opposed to the rest) on the platform's text editing (native or browser) as opposed to doing it yourself.

https://faultlore.com/blah/text-hates-you/

https://lord.io/text-editing-hates-you-too/

**Comment by makepaddev** [comment]
We have platform IME support on web and apple, but there are a couple of dependencies we are working on.
- Platform IME on linux / windows needs implementing
- Font layouting/shaping (harfbuzz like)
- Emojis

However yes we are aware this is a problem. Last resort we'll pull in more of the platform.

**Comment by greggman** [comment]
I tried it on web, at least the live version. Emoji were ignored on paste. japanese was not enterable. At least for me on MacOS 13 in Chrome 113

**Comment by makepaddev** [comment]
We cant render emoji yet. For web IME i tried to use the same method a code editor uses like ACE. Does japanese work here:
https://ace.c9.io/build/kitchen-sink.html 
If it works here then its the font rendering (it doesnt have a japanese font).
Doing a file-new stack definitely has challenges there but i think we'll get there over time.

**Comment by makepaddev** [comment]
Mobile web text entry is an entirely different and worse problem because of the sliding keyboard. This problem might actually not be entirely fixable, unlike native. Last time i tried iOS-safari was buggy as hell.

**Comment by greggman** [comment]
I'm not sure what you mean you use the same input as ACE. ACE is HTML based, not canvas based, at least from the link you sent me. So it works with IMEs and Japanese, and emoji just fine. (tested)

**Comment by makepaddev** [comment]
My point is i use the same text-input control as ACE. So if ACE can do it its a rendering issue and we can do it with enough effort. If not its a text input widget issue.

**Comment by makepaddev** [comment]
Btw this problem is well known to us. However i refuse to give up trying to create something better for rendering UI than HTML because it's a huge investment to get right.

**Comment by greggman** [comment]
It's extremely hard to get right. For a few small uses cases it's okay to render your own text but using the platform's system means the text is available for all the platform's features. For example on MacOS if I select some text and right click I get some menu like this

<img width="240" alt="Screenshot 2023-05-22 at 14 24 05" src="https://github.com/makepad/makepad/assets/234804/5eb033cf-d02f-45c5-b60b-cba8b0d15a97">

Most of which is provided by the OS and changes with each version of the OS as new features are added. The app does not have to be aware of the features and usually is not aware of them.

In most cases, (a code editor possibly being an exception), the only way that works is if you use the platform's text editing because the platform needs to know what the text is, not just a block of pixels. It can't offer accessibility features like "Speech->Start Speaking" or internationalization features like "Translate ..." or  educational/accessibility/internationalization features like "Look up ..." without more than just some pixels.

There are other issues too like *reconversion*. You're supposed to be able to select some text and press Shift-Ctrl-R to bring that text back into the IME to choose another completion

https://github.com/makepad/makepad/assets/234804/49ef731a-899f-4e9f-8c1c-b68fda3fe378

In any case, you mentioned CJK support for web but at least for me 

1. nothing appears at https://makepad.dev when I try to enter Japanese.
2. Even tho I pressed n i h o n the characters that appeared in the IME were unrelated. it seems like the first key (n) didn't make to the IME
3. The IME ends up moving to the top left of the window
4. The page usually hangs



https://github.com/makepad/makepad/assets/234804/1eaa6526-7224-4669-b3f7-f3f8e2aa9fd5

**Comment by shiro** [comment]
Also tested https://makepad.dev on firefox linux xorg using Fcitx as the IME, the suggestion window is in the correct position and works fine, the preview is not rendered and the site freezes after confirming an entry.

On a side note, pasting japanese text doesn't freeze but just displays the characters as blank spaces, probably it's not in the font range.

**Comment by tkkcc** [comment]
i test https://makepad.dev/ on chromium linux x11, fcitx5 chinese input is fine, except is rendered in blank, probably a font range problem.

i test makepad-example-simple's text input on android, soft and hard keyboard both works, but ime is forced in engligh mode, not system default language.

**Comment by jason-yau** [comment]
Was it fixed?

**Comment by makepaddev** [comment]
No, it will take some time. Makepad.dev is almost 4 years old so its an unrelated codebase at this point.

**Comment by yulnr** [comment]
Closing this issue as we now have support for entering and displaying text in those languages. 
I believe emoji support is in the works.

**Comment by zxhd863943427** [comment]
Tested on 2025.06.24, at least https://makepad.dev/ can't input and display CJK on Windows 10 firefox.
