### ISSUE TITLE
x86/x86_64 arch support for android

### ISSUE THREAD

**Issue by tkkcc** [makepad/makepad#191]
I want to run makepad-example-ironfish on android x86_64 emulator.

arm64 arch is hardcoded in `tools/cargo_makepad/src/android/compile.rs`. I modify aarch64 to x86_64 and arm64 to x86_64. But got this strange error. (on rik branch)

```txt
  --> libs/error_log/src/error_log_android.rs:24:9
   |
24 |         __android_log_write(3, "Makepad\0".as_ptr(), val.as_ptr());
   |         ^^^^^^^^^^^^^^^^^^^
   |
note: expected `*const i8`, found `*const u8`
  --> libs/error_log/src/error_log_android.rs:24:32
   |
24 |         __android_log_write(3, "Makepad\0".as_ptr(), val.as_ptr());
   |                                ^^^^^^^^^^^^^^^^^^^^
   = note: expected raw pointer `*const i8`
              found raw pointer `*const u8`

```

**Comment by makepaddev** [comment]
Ah yea, apparently the type of as_ptr() changes between those 2 platforms, meaning i use the wrong type in the function declaration of __android_log_write. You'd have to figure out what type to use for as_ptr() its probably something from std::ffi instead of hardcoding *const i8 on the C function.

**Comment by makepaddev** [comment]
feel free to investigate, otherwise i can have a look

**Comment by makepaddev** [comment]
Also the android toolchain install function does not for now copy the x86 tooling either, but i assume you fixed that?

**Comment by makepaddev** [comment]
It's not super hard but the makepad-cargo android stuff needs quite a lot of changes to support multiple android targets

**Comment by makepaddev** [comment]
I'll fix up the toolchain installer to include all relevant android targets

**Comment by tkkcc** [comment]
I can make it run on x86_64 emulator now. following your advice, i switch the linker and aapt path, and comment out the __android_log_write.

**Comment by makepaddev** [comment]
Alright im just fixing it up so it'l compile out of the box

**Comment by makepaddev** [comment]
I've added support for installing the toolchains/targets. Haven't done the compiling bit yet

**Comment by jmbejar** [comment]
@tkkcc We were working on improving Android build to support x86_64 emulator and others. However, we would accept some help to test.

Could you try the change from this PR #193 on your side? So we know if it's good enough to be merged or something else must be fixed.

**Comment by tkkcc** [comment]
I test these commands, yes, it works on x86_64 android 11 emulator.
```sh
cargo run -p cargo-makepad --release -- android --abi=all toolchain-install
cargo run -p cargo-makepad --release -- android --abi=x86_64 run -p makepad-example-ironfish
cargo run -p cargo-makepad --release -- android --abi=all run -p makepad-example-ironfish
```
---
There are some other issues, i just note here.

1. if adb devices has more than one devices, run will fail with
    ```txt
       Compiling makepad-synth-ironfish v0.3.0 (/home/bilabila/bin/makepad/examples/ironfish/synth_ironfish)
       Compiling makepad-audio-widgets v0.3.0 (/home/bilabila/bin/makepad/audio_graph/audio_widgets)
       Compiling makepad-example-ironfish v0.3.0 (/home/bilabila/bin/makepad/examples/ironfish)
        Finished release [optimized] target(s) in 11.90s
    Compiling APK & R.java files
    Building APK
    Compile APK completed
    Got error: Process /home/bilabila/bin/makepad/tools/cargo_makepad/./android_33_linux_x64/platform-tools/adb in dir "/home/bilabila/bin/makepad" returned error exit code adb: more than one device/emulator
    ```
    i use ANDROID_SERIAL to specific one of them and it's fine.


2. run fail for android 7 (x86 and aarch64)
    [tmp.log](https://github.com/makepad/makepad/files/12129869/tmp.log)
    > java.lang.UnsatisfiedLinkError: dlopen failed: library "libaaudio.so" not found

**Comment by tkkcc** [comment]
for android 7, i also test other demos, similar lib missing with a bit different

```txt
07-21 10:48:53.667  2054  2054 E AndroidRuntime: Process: dev.makepad.makepad_example_ironfish, PID: 2054
07-21 10:48:53.667  2054  2054 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libaaudio.so" not found
07-21 10:48:53.667  2054  2054 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
07-21 10:48:53.667  2054  2054 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1530)

07-21 11:01:34.364  2350  2350 E AndroidRuntime: Process: dev.makepad.makepad_example_widgets, PID: 2350
07-21 11:01:34.364  2350  2350 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libamidi.so" not found
07-21 11:01:34.364  2350  2350 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
07-21 11:01:34.364  2350  2350 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1530)


07-21 11:00:18.812  2288  2288 E AndroidRuntime: Process: dev.makepad.makepad_example_numbers, PID: 2288
07-21 11:00:18.812  2288  2288 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libamidi.so" not found
07-21 11:00:18.812  2288  2288 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
07-21 11:00:18.812  2288  2288 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1530)


07-21 10:59:41.041  2231  2231 E AndroidRuntime: Process: dev.makepad.makepad_example_simple, PID: 2231
07-21 10:59:41.041  2231  2231 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libamidi.so" not found
07-21 10:59:41.041  2231  2231 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
07-21 10:59:41.041  2231  2231 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1530)
```

**Comment by tkkcc** [comment]
maybe notify developers a supported version list of android, somewhere.

**Comment by jmbejar** [comment]
Awesome amount of feedback! Thanks for testing. 

> if adb devices has more than one devices, run will fail with

We could add another param to our build script to pass the `-s` to `abd`. At the same time, it is controllable via `ANDROID_SERIAL` env var, so I'm not sure 

> maybe notify developers a supported version list of android, somewhere.

Agreed!

**Comment by tkkcc** [comment]
yes, `-s` is like what `scrcpy` use. and args have higher priority than envs. and stop and tell user if it can't decide. 
ok, it's just what `scrcpy` does. it's not very creative, but fine. hahaha
