### ISSUE TITLE
Unable to compile the examples to native on Mac Os 10.14

### ISSUE THREAD

**Issue by Solcany** [makepad/makepad#192]
I'm trying to compile the examples on a 2017 Macbook Pro with 10.14.16 Mac Os.  I tried compiling with the stable 1.70.0 and the nightly 1.73.0-nightly rust builds. Using the  `cargo run -p makepad-example-simple --release` command. The web build was successful.

The error:
`error: linking with "cc" failed: exit status: 1
 note: Undefined symbols for architecture x86_64:
            "_MIDIInputPortCreateWithProtocol", referenced from:
                makepad_platform::os::apple::core_midi::CoreMidiAccess::new::h6709ae4d0ca0d543 in libmakepad_platform-211f04c7388cd123.rlib(makepad_platform-211f04c7388cd123.makepad_platform.e1ac5467-cgu.14.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by makepaddev** [comment]
Hi, we are currently on macos 13.4.1 so that is about 3000 versions ago. Really old macOS is very annoying because of reasons like this. Also metal API changes / shader compiler changes so badly nothing works anymore. I don't really see a good reason to support OS'es this old

**Comment by makepaddev** [comment]
You can always comment out/stub out the import and see if it works then. My guess is its not just a missing MIDI api.

**Comment by makepaddev** [comment]
to do so do this:
remove pub fn MIDIInputPortCreateWithProtocol( from the "extern "C" block in platform/src/os/apple/apple_sys.rs (line 1166)
And move it in the root scope (move it to line 1141) and do
    pub fn MIDIInputPortCreateWithProtocol(
        _client: MIDIClientRef,
        _portName: CFStringRef,
        _protocol: MIDIProtocolID,
        _outPort: *mut MIDIPortRef,
        _receiveBlock: ObjcId,
    ) -> OSStatus{return 0;}

**Comment by makepaddev** [comment]
As a general aside i wouldn't recommend running an OS this old just for the security updates yr missing.

**Comment by Solcany** [comment]
Thank you for the quick reply. OS update fixed the issue.
