### ISSUE TITLE
Issues building ironfish for webassembly on macOS

### ISSUE THREAD

**Issue by coolbluewater** [makepad/makepad#202]
Hi, long time!
I've built ironfish natively for macos and it runs well.
However, building for webassembly has a few issues:
1. The URL is no longer the one in the README, and `0.0.0.0:61234` does not work on my mac.
2. When I changed it to `127.0.0.1:8089` the browser was able to connect. However displays the initialization message indefinitely. The developer console shows that it is unable to load the resource cx_webgl.js.

I am able to run the demo link, so this looks like a local build/run issue.
Also noticed that the `rik` branch is 350 or so commits of main, so tried changing to that, but to no avail. Get a bunch of other errors.

Cheers

**Comment by makepaddev** [comment]
Hm thats not right. Let me check. Tried branch rik and works fine here.
./tools/wasm/build_wasm_thread.sh makepad-example-ironfish
then connect to it with a local http server, but be sure the thing serves wasm files properly.

**Comment by coolbluewater** [comment]
Appreciate if you could list the steps and URL for the "works fine" case :)

**Comment by coolbluewater** [comment]
Here's the compiler error I'm seeing:
```
error[E0433]: failed to resolve: use of undeclared crate or module `std`
   --> /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-adler32-0.3.7/src/imp/wasm.rs:146:34
    |
146 |     let arr: [u32; 4] = unsafe { std::mem::transmute(v) };
    |                                  ^^^ use of undeclared crate or module `std`
    |
help: consider importing this module
    |
28  +   use core::mem;
    |
help: if you import `mem`, refer to it directly
    |
146 -     let arr: [u32; 4] = unsafe { std::mem::transmute(v) };
146 +     let arr: [u32; 4] = unsafe { mem::transmute(v) };
    |
```

**Comment by makepaddev** [comment]
I fixed up the webserver here, so the 61234 works again here. Not seeing that compile error. Let me update Rust and see

**Comment by makepaddev** [comment]
Use branch rik to pull from

**Comment by makepaddev** [comment]
See this is why i dont use external dependencies. That crate is not mine.

**Comment by coolbluewater** [comment]
Roger that, dependencies are the gift that keeps on giving. :)

**Comment by makepaddev** [comment]
Ok so i dit rustup update and im not seeing any errors i suggest you do the same

**Comment by makepaddev** [comment]
Make sure you have all the wasm stuff installed eh like the standard library

**Comment by makepaddev** [comment]
I can't repro it

**Comment by coolbluewater** [comment]
Just did `rustup update` which updated a few things. Then deleted the `target` dir.
The error persists. I thought it was a missing -Zbuild-std but your shell script has that. Will keep on digging.

Also, why did the URL change to 0.0.0.0? Anything special needed to connect to these URL's? I've tried to understand the difference between 0.0.0.0 and 127.0.0.1 but am still don't have a good idea - is it that the former allows external connections but the latter does not?

**Comment by coolbluewater** [comment]
In the meantime, any idea about the problem in the initial post regarding `master` and the missing resource?

**Comment by coolbluewater** [comment]
Also, I'm building on an M1 mac with an arm64 toolchain (not Rosetta2) if that makes any difference.

**Comment by makepaddev** [comment]
Master is too old i need to merge it in i dont know whats up there Rust nightly ages very quickly

**Comment by coolbluewater** [comment]
So the `rik` branch is the one to use, got it. Suggest updating the URL when you make the merge. I am going to try checking out the simd-adler32 crate locally and patching it, fingers crossed.

**Comment by makepaddev** [comment]
i have no idea why it works fine here and not for you

**Comment by coolbluewater** [comment]
Update: was able to get the build to complete by changing line 146 from the original problem (changed `std` to `core`:
```
-    let arr: [u32; 4] = unsafe { std::mem::transmute(v) };
+    let arr: [u32; 4] = unsafe { core::mem::transmute(v) };
```

Next step: to try running it!

**Comment by coolbluewater** [comment]
Ugh, the browser still cannot connect to `https://0.0.0.0:61234/makepad/examples/ironfish/src/index.html` even though the server is listening on that port.

**Comment by makepaddev** [comment]
Well thats because there is no https AND no 0.0.0.0
try http://127.0.0.1:61234

**Comment by coolbluewater** [comment]
Is that the full URL? :)

**Comment by makepaddev** [comment]
http://127.0.0.1:61234/makepad/examples/ironfish/src/index.html

**Comment by coolbluewater** [comment]
Ok, so now I get the Loading... message and this browser console error:
```
Failed to load resource: net::ERR_EMPTY_RESPONSE
wasm_bridge.js:196 TypeError: Failed to fetch
    at WasmWebGL.fetch_and_instantiate_wasm (wasm_bridge.js:192:45)
    at index.html:10:38
(anonymous) @ wasm_bridge.js:196
wasm_bridge.js:5 Wasm object is undefined, check your URL and build output
WasmBridge @ wasm_bridge.js:5
WasmWebBrowser @ web.js:5
WasmWebGL @ web_gl.js:5
MyWasmApp @ index.html:17
(anonymous) @ index.html:21

```

**Comment by coolbluewater** [comment]
Safari gives a more understandable error (I can't seem to copy it so had to type it out, typos beware)
```
[Error] Failed to load resource   http://127.0.0.1:61234/makepad/target/wasm32-unknown-unknown/release/makepad-example-ironfish.wasm
```
The wasm file does not exist at this location but it *does* exist at `makepad/target/wasm32-simd/wasm32-unknown-unknown/release`. That is, there's a`wasm32-unknown-unknown` folder underneath `wasm32-simd` caused by this code in `build_wasm_simd.sh`: 
```
CARGO_TARGET_DIR=target/wasm32-simd 
```

I'm confused why you're not also seeing this error - do you have an old build artifact at the location the browser expects?

**Comment by makepaddev** [comment]
did you run this:
./tools/wasm/build_wasm_thread.sh makepad-example-ironfish

**Comment by makepaddev** [comment]
that should create that wasm file in the right spot

**Comment by makepaddev** [comment]
You cant run a wasm-simd build for safari, it doesnt support that. ironfish only needs threads

**Comment by coolbluewater** [comment]
> did you run this:
> ./tools/wasm/build_wasm_thread.sh makepad-example-ironfish

The README says `./tools/wasm/build_wasm_simd.sh makepad-example-ironfish` :)
It also says `https://127.0.0.1:8080/makepad/examples/ironfish/src/index.html` with the `https` AND `8080` :)

I will try your command line. Fingers crossed

**Comment by makepaddev** [comment]
Lame. now it doesnt anymore.

**Comment by coolbluewater** [comment]
... and that worked! So I guess this thread was pilot error due to the README?

**Comment by makepaddev** [comment]
Seems to be :)

**Comment by coolbluewater** [comment]
No problem, it happens :). I tried pulling from `rik` but the README has not changed.

**Comment by makepaddev** [comment]
i did it in master.

**Comment by coolbluewater** [comment]
You mentioned earlier that `master` may be broken and `rik` is the working branch. If so it's clearer to:
1) Update the README in rik with the proper build commands and URL, and 
2) Update the README in 'master' redirecting folks to 'rik'.

Otherwise this issue, that I've been happy to investigate for the last couple of hours, does not really feel closed and the next guy is not helped.
