### ISSUE TITLE
Webassembly build instructions broken again in README?

### ISSUE THREAD

**Issue by coolbluewater** [makepad/makepad#211]
Hey, is the webassembly URL broken in the README in `master`?
I've spent some time trying to figure this out again, could you take a quick look please?
The URL says `https` and `127.0.0.1` and I thought the last we spoke the correct one is `http` and `0.0.0.0`?

Also I'm trying to run the news-feed webassembly app - is it supposed to work.

**Comment by makepaddev** [comment]
I thought i just changed that. lets see.

**Comment by makepaddev** [comment]
Now it should be ok.

**Comment by makepaddev** [comment]
Somehow https snuck back in. But the link should work the way it is now.

**Comment by coolbluewater** [comment]
That doesn't work - the webserver says 0.0.0.0.

**Comment by makepaddev** [comment]
One of these days well have an IDE that manages all this wrangling for you and can open a browser for the wasm build it generates.

**Comment by makepaddev** [comment]
Hmm really. let me see.

**Comment by makepaddev** [comment]
Pull and retry, odd it is indeed binding to 0.0.0.0 but that does work here on my pc. I now set it to bind to 127.0.0.1

**Comment by makepaddev** [comment]
0.0.0.0 is supposed to bind to all your ips.

**Comment by makepaddev** [comment]
I use it to test on phones on my LAN.

**Comment by makepaddev** [comment]
Apparently on your machine 0.0.0.0 doesnt bind to 127.0.0.1.

**Comment by coolbluewater** [comment]
gtg, will try it later. From what I've read 0.0.0.0 and 127.0.0.1 are very different beasts.
BTW I sent a pull request.

**Comment by makepaddev** [comment]
Thx

**Comment by coolbluewater** [comment]
Before I go a) does news-feed work on webassembly and b) what are you trying to achieve with 0.0.0.0?

**Comment by makepaddev** [comment]
i dont think i tried news-feed on wasm no it should work but it might miss some paths in the html.
ironfish is the only one i test on wasm for now.
I'll fix it in a sec. Also 0.0.0.0 'afaik' binds to all your ips. both internal and external i use it so i can open a link to the webserver on my phone on my lan.

**Comment by makepaddev** [comment]
Ok fixed news feed. also webserver didnt mime jpegs yet now it does

**Comment by coolbluewater** [comment]
Thanks. 
My app will be built in a separate repo, so a question about the webserver. Where does it assemble the files, and can I use a regular webserver to serve up the static site?

If not, where in the server code does it map request URL's to code paths? I can try to generalize the server to accept an externally defined mapping.

**Comment by makepaddev** [comment]
You can use any server you want really. The webserver is really nothing special and should be trivial to read how it processes the urls. It mostly just serves the makepad/ url.

**Comment by coolbluewater** [comment]
I tried it on news-feed but the paths don't match up. Where should I serve the root from?

**Comment by makepaddev** [comment]
So you have to serve the entire repo from makepad/ 
127.0.0.1:port/makepad/examples/etc
I think thats how i set it up. Shouldnt be that hard to change that up tho

**Comment by makepaddev** [comment]
I'd have to check how it maps the DSL dependency paths. It was a WIP

**Comment by coolbluewater** [comment]
What I'd like to do is to run a plain old python server via e.g. `python -m http.server 8004` from whatever root and with whatever port, if that matters.

**Comment by makepaddev** [comment]
Yea so it should work if you put the makepad repo in a makepad folder and just serve from the one dir up.

**Comment by makepaddev** [comment]
so /makepad/.. works

**Comment by makepaddev** [comment]
also the python server needs to send the right headers + wasm mime types and all that. check my webserver for examples

**Comment by makepaddev** [comment]
Cross-Origin-Embedder-Policy: require-corp\r\n\
                                Cross-Origin-Opener-Policy: same-origin\r\n\

these 2 things are important for allowing wasm to create threads for instance.

**Comment by coolbluewater** [comment]
I managed to get those two things but think I need to deal with the mime types.

To avoid duplication of effort, now that you've examined the code does it seem doable to run your server from a makepad app built outside the normal tree? That's what I'd really like to do.

**Comment by coolbluewater** [comment]
Also, where are the generated .wasm files placed at?

**Comment by makepaddev** [comment]
wasm files go in: in target/...
it'l say where exactly after you run the ./tools/wasm/build thing
As for run the webserver out-of-tree yea its possible the webserver is only a page of code in terms of pathwrangling. feel free to change it to whatever you want

**Comment by makepaddev** [comment]
The webserver will be depricated and integrated in our IDE and wasmbuildtool soon to solve this problem. But its not on my immediate todostack.

**Comment by coolbluewater** [comment]
I will, but please explain where all the bits are served from. It looks like there are some bits in the source tree and some in `target/`.

**Comment by coolbluewater** [comment]
Just a short clear description assuming that I've forgotten everything I think I know, please.

**Comment by makepaddev** [comment]
essentially i serve the entire repo root under makepad/ so you can reach all the files in the subcrates + the target/ directory

**Comment by makepaddev** [comment]
Yea this pathwrangling is a bit finnicky. We havent finished our wasm buildtool yet that would straighten this up for external builds.

**Comment by coolbluewater** [comment]
I don't know what you are saying. Please use clear English as "bit finnicky" can mean anything. I am trying to actually get this done.

**Comment by coolbluewater** [comment]
I just need to know what needs to be done, clearly and simply please.

**Comment by makepaddev** [comment]
Yea im trying to say that i havent built the bits yet that allow you to do this easily. I use compiletime path generation and then have to map that to what your webserver gives back. And i use the paths of the makepad 'git' repo. This needs a packaging tool for this to ship.

**Comment by makepaddev** [comment]
The packaging tool called cargo-makepad which is stubbed out for wasm at this point in time.

**Comment by coolbluewater** [comment]
Is all that needed just to serve the files, or for live editing? I am not interested in live editing at the moment.

**Comment by makepaddev** [comment]
No its because i use dependencies IN crates under the resources/ folder. So if you want to serve this over http you need that path to be accesible to a webserver. Right now i just solve it by having all the crates IN the makepad repo so i can just use the paths inside the git repo. The moment you move the makepad crates elsewhere (like on crates io) this changes. You then need a buildtool to collect them for you or a webserver that understands how to serve these things

**Comment by makepaddev** [comment]
So when you change the directory of makepad whilst still doing wasm builds outside of it, yr breaking my path handling for this quickfix of being able to build wasm examples. The real case needs a build / collection tool or a customized webserver (we will make botH)

**Comment by makepaddev** [comment]
If you want this now tho the only easy way to go is run a makepad example, look at the http paths it fetches and if you use a different server make sure it can serve those files from the same place.

**Comment by coolbluewater** [comment]
I am just trying to bootstrap an app since yesterday to build and run a) for macOS and b) for webassembly, but building from my own repo. For starters I want to just copy the entire newsfeed app and change the path to the relevant makepad crates to point to the makepad repo. What is the simplest way to get this to work? Can I make a couple of symlinks from the makepad repo to folders within my repo's source and target folders? If so, exactly what symlinks do I need to create?

**Comment by makepaddev** [comment]
Honestly i'd have to try to do the exact same thing and see what i run into.

**Comment by makepaddev** [comment]
Lets see.

**Comment by makepaddev** [comment]
Ok so for macos all you need to do is just checkout the repo under a makepad/ directory in your project and then put this in your Cargo.toml

[workspace]
[dependencies]
makepad-widgets = { path = "./makepad/widgets", version = "0.3.0" }

**Comment by makepaddev** [comment]
Now lets try wasm

**Comment by coolbluewater** [comment]
So *my* code needs to be in a folder named `makepad`? A tree outline would kinda help. I've already got the `makepad` folder checked out in a `deps/makepad` subfolder. Here's the outline I'm thinking of

```
rust
+ deps
   + makepad (your repo)
+ my_app <-- a clone of news_feed
   + Cargo.toml (the entries for the makepad crates point inside deps/makepad)
```

**Comment by makepaddev** [comment]
No your code is the rootnode. You checkout the makepad repo in the makepad/ directory in your repo root.  like
Cargo.toml
src/
makepad/

**Comment by makepaddev** [comment]
So macos runs fine with that. Wasm also compiles but i had to change the shellscript so it doesnt use the -p (this project doesnt have a workspace)

**Comment by makepaddev** [comment]
However serving this thing with a webserver is going to require some path remapping. Either i code that into mine or you need to figure this out.

**Comment by makepaddev** [comment]
Btw your tree is also possible but then you get the problem that you need to ../deps/makepad everywhere so now the remapping is going to be even harder in a webserver.

**Comment by makepaddev** [comment]
You can just put this in your Cargo.toml:
[dependencies]
makepad-widgets = { path = "../deps/makepad/widgets", version = "0.3.0" }

**Comment by makepaddev** [comment]
That will build the macos things perfectly fine

**Comment by makepaddev** [comment]
I'll mirror your structure

**Comment by coolbluewater** [comment]
So is this it?

```
rust
+ my_app
  + Cargo.toml (with `makepad-widgets = { path = "./makepad/widgets", version = "0.3.0" }`
  + makepad (your repo)
```

What is the app URL?

**Comment by coolbluewater** [comment]
Ok I'll wait for you to try my earlier structure, thanks.

**Comment by makepaddev** [comment]
Ok i mirrored your way. You can do
```
+deps
     +makepad
+myapp
     Cargo.toml
     
Then make this your Cargo
-----
[package]
name = "makepad-example-news-feed"
version = "0.3.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad news feed example"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "5POKajmZt90sjG2MIw5C9dizbBo="

[dependencies]
makepad-widgets = { path = "../deps/makepad/widgets", version = "0.3.0" }

[workspace]
-----     
```

**Comment by makepaddev** [comment]
now you can type in my_app
cargo run --release

And you should see the newsfeed app working. So that takes care of macos.

**Comment by makepaddev** [comment]
Now lets tackle building the wasm file.

**Comment by coolbluewater** [comment]
Possible to edit your earlier comment and show the tree structure in monospace with the `rust` folder as the root? You can get monospace with the code formatting style (three backticks above and below.)

**Comment by makepaddev** [comment]
Done

**Comment by makepaddev** [comment]
now ill fix the wasm build script so it atleast compiles. The rest of the problem is serving it

**Comment by makepaddev** [comment]
Ok if you pull 'rik' branch you will get this tool to run from your 'my_app' i fixed it up so it doesnt use a -p 
../deps/makepad/tools/wasm/build_wasm_thread.sh 
This will generate a wasm file in target/... in your project.

**Comment by makepaddev** [comment]
So now you have a wasm file, except now you need a webserver that can reach all the dependencies that the makepad thing wants. Which are a bunch of font files / images and the js/css files inside the makepad repo. Here you kinda need to config your webserver to map some paths i think.

**Comment by makepaddev** [comment]
I would load up ironfish or something inside the repo 'that works' and check the paths and make a remap

**Comment by coolbluewater** [comment]
Wait, I thought the idea was to use `makepad-webserver`?

**Comment by makepaddev** [comment]
oh you dont want python?

**Comment by makepaddev** [comment]
k lets see if i can modify the thing

**Comment by makepaddev** [comment]
it will work like this in makepad repo: 
cargo build -p makepad-web-server --release
then in yours do
../deps/makepad/target/release/makepad-web-server ../deps/makepad/
so the thing knows the makepad path. Ill fiddle it to work. sec

**Comment by makepaddev** [comment]
Ok there you go. Pull my branch then do what i said above mind the trailing / on the makepad path otherwise it doesnt work

**Comment by makepaddev** [comment]
i made a little path remapper in the webserver

**Comment by coolbluewater** [comment]
Great! What is my app's URL?

**Comment by makepaddev** [comment]
http://127.0.0.1:61234/src/index.html

**Comment by makepaddev** [comment]
the root is the cwd of where you run the webserver

**Comment by coolbluewater** [comment]
Got it.

**Comment by makepaddev** [comment]
Hmm hold up for a sec

**Comment by makepaddev** [comment]
I have to verify for a sec that i didnt just load the wrong wasm file.

**Comment by makepaddev** [comment]
Yea ok thats not good yet. sec

**Comment by makepaddev** [comment]
Yea exactly sec. my path remapping of the wasm file-s resources is not working yet.

**Comment by coolbluewater** [comment]
Ok. Got the macOS app running.

**Comment by makepaddev** [comment]
Ok there you go try it now. Please know that you cant symlink the deps/makepad repo it'l fail.

**Comment by makepaddev** [comment]
Rusts 'canonicalise' that flattens the ../ path also flattens symlinks. Otherwise it works

**Comment by coolbluewater** [comment]
This solution does not involve any symlinks, correct?

**Comment by makepaddev** [comment]
It does not. However the path you give to webserver needs to be relative to your directory. I did the path processing that way.

**Comment by makepaddev** [comment]
And that relative path cannot hop any symlinks otherwise it also breaks.

**Comment by makepaddev** [comment]
I have to webserver-side translate the compiled-in paths for crate resources.

**Comment by makepaddev** [comment]
news feed gives some errors.

**Comment by coolbluewater** [comment]
What is the webassembly build command?

**Comment by makepaddev** [comment]
../deps/makepad/tools/wasm/build_wasm_thread.sh

**Comment by coolbluewater** [comment]
I vote we abandon this ultra hacky approach and emit a real static website in the file system.

**Comment by makepaddev** [comment]
Well yea we're going to pick up wasm buildtooling to do this proper but you wanted it to work now

**Comment by makepaddev** [comment]
There i fixed some errors in news_feed it was spewing and the wasm build script. Either way you have it working now?

**Comment by coolbluewater** [comment]
> Well yea we're going to pick up wasm buildtooling to do this proper but you wanted it to work now

I will try to do it now. This is way too hacky for my taste. Why spend these minutes and hours on the wrong approach?
Possible to write out the exact static website file tree for the news-feed app without omitting a single file?

**Comment by makepaddev** [comment]
The problem is as i compile the application in Rust i access absolute paths for the resources. You can try to fix it but i'm going to continue on what im doing now. We have a project for the cargo-makepad build tool to resolve this in due time.

**Comment by makepaddev** [comment]
Did you manage to run the wasm project now?

**Comment by coolbluewater** [comment]
I am just asking for the problem statement to be explained with all necessary detail. If these are provided I can work on a solution.

**Comment by coolbluewater** [comment]
> Did you manage to run the wasm project now?

Will give it a shot.

**Comment by makepaddev** [comment]
I don't have a clear def yet it'l take me some time to come up with a resource packaging plan accross all the platforms we have which includes android and ios as well. It's not something i can just solve like that its on the todo to fix properly.

**Comment by coolbluewater** [comment]
I mean, what does the webserver do right now, exactly?

**Comment by makepaddev** [comment]
It simply remaps paths you throw at it to the right folder for what you wanted to do. Which means remap /makepad/ to the makepad repo directory, and it also has /makepad//fullabspath/ in there from Rust compilers WASM output since i dont have relative paths to resources at compiletime. Need to fix this up somehow.

**Comment by makepaddev** [comment]
In our DSL you can write thigns like this
dep("crate://makepad-widgets/resources/GoNotoKurrent-Regular.ttf")
However that crate:// expands to the absolute path of the crate, since otherwise i cant reference fonts from a cargo deploy of makepad. But for wasm this doesnt work since it needs some kind of packaging-table

**Comment by makepaddev** [comment]
Either way its a project wide issue i need to resolve at some point integrated with cargo-makepad buildtooling. I'll get around to it in the near future.

**Comment by makepaddev** [comment]
Right now i cheat by just accepting the 'full path' on the webserver and stripping it out serverside. You could also choose to strip this out on the webbrowser side. Or it can be fixed at the Rust level. Either way its something to solve.

**Comment by coolbluewater** [comment]
Isn't this essentially just a handful of URL to folder mappings? Possible to just state these mappings in a short table? Not asking for anything but exact info here...

**Comment by makepaddev** [comment]
Well thats what the webserver now does for you because it knows a bit more about the path-name-environment than the browser code. But ideally we clean this up more nicely. I dont have the mindspace to solve that now, will do so later.

**Comment by coolbluewater** [comment]
Yes, I am just asking for the exact set of mapping rules that the webserver is using right now. Just a short table, please.

**Comment by makepaddev** [comment]
It's at the top of webserver main.rs

**Comment by makepaddev** [comment]
```
    let remaps = [
        (format!("/makepad/{}/",abs_makepad_path),makepad_path.clone()),
        (format!("/makepad/{}/",std::env::current_dir().unwrap().display()),"".to_string()),
        ("/makepad//".to_string(),makepad_path.clone()),
        ("/makepad/".to_string(),makepad_path.clone()),
        ("/".to_string(),"".to_string())
    ];
```

**Comment by coolbluewater** [comment]
Can you explain just one of these lines fully, please? The devil is always in the details.

**Comment by makepaddev** [comment]
is a table that replaces the left part in the url path with the right part if it matches (its for looped down below)

**Comment by makepaddev** [comment]
if yr curious how it remaps just println paths below and run the server

**Comment by coolbluewater** [comment]
Anyway I tried running the webassembly and am getting load errors, more info on the way.

**Comment by coolbluewater** [comment]
It is requesting the .wasm file at ` http://127.0.0.1:61234/makepad/target/wasm32-unknown-unknown/release/my_app.wasm
` - is this correct?

**Comment by makepaddev** [comment]
no it is not. you should update your news_feed example copy

**Comment by makepaddev** [comment]
Hmm wait

**Comment by makepaddev** [comment]
Yea i didnt commit that the index.html needs the /makepad/ removed from its wasm path

**Comment by makepaddev** [comment]
now i did

**Comment by makepaddev** [comment]
"/target/wasm32-unknown-unknown/release/makepad-example-news-feed.wasm"

**Comment by makepaddev** [comment]
line 11 in index.html

**Comment by makepaddev** [comment]
/makepad/ is now treated as special to point to our repo.

**Comment by coolbluewater** [comment]
It's now requesting `http://127.0.0.1:61234/target/wasm32-unknown-unknown/release/my_app.wasm` as expected but still can't find it. Where is the server expecting this to be?

**Comment by makepaddev** [comment]
in your current working directory under target/wasm32-unknown...
Does that file exist?
its supposed to be generated by the 
../deps/makepad3/tools/wasm/build_wasm_thread.sh

**Comment by coolbluewater** [comment]
Ah - I made a typo. (The old rust hyphen vs underscore nightmare.) Works now. Wow.

**Comment by makepaddev** [comment]
Well thanks for your patience. Do know that this is not intent to ship.

**Comment by makepaddev** [comment]
It's just not done yet.

**Comment by makepaddev** [comment]
But atleast it works now for this way of playing with it.

**Comment by coolbluewater** [comment]
This def unblocks me for the moment. The 'basic hurdle', as K&R would say.

**Comment by coolbluewater** [comment]
Thanks a lot.

**Comment by makepaddev** [comment]
Yw

**Comment by coolbluewater** [comment]
Definitely feels like a significant moment. A lot of creativity being unleashed.

**Comment by makepaddev** [comment]
btw im in the middle of making my text input control do wordwrapping. should be done in a day or so but if you track 'rik' it will be a bit janky

**Comment by coolbluewater** [comment]
Ok. BTW I'm now getting this spew when running the macOS build, which is causing the app to  run slow:
```
rust/deps/makepad/platform/src/live_cx.rs:158:13 - Apply error: src/app.rs: 4:4849 - no matching field: layout
```
Are you seeing the same thing?

**Comment by makepaddev** [comment]
If you compile like this it will show you a proper line nr
MAKEPAD=lines cargo +nightly run ...
Just remove that layout: at that position we changed the image widget.

**Comment by makepaddev** [comment]
Also you kindof need releasebuilds for it to be fast. We're fixing that debug builds arent so bad, but since rustybuzz its unusably slow

**Comment by coolbluewater** [comment]
Ok, one of those lines is `app.rs:192` which is this line within an `<Image>`:
```Rust
                    layout: {padding: 0}
```

**Comment by makepaddev** [comment]
Yea just delete that line.

**Comment by coolbluewater** [comment]
1) There are dozens of such lines
2) The news_feed app doesn't emit this spew. So it looks like there's some issue building/running the app from my repo.

**Comment by makepaddev** [comment]
yes there are dozens of lines i fixed already but your copy of news_feed was before i did that

**Comment by makepaddev** [comment]
Also there are only two, but it just emits the error a lot

**Comment by coolbluewater** [comment]
Ah I see, will diff with news_feed. Tks!

**Comment by makepaddev** [comment]
just delete the layout: line in the Image things

**Comment by guofoo** [comment]
Makepad's WASM build had been updated and currently works. Please let us know if this is still an issue.
