### ISSUE TITLE
Some thoughts, from a QML user.

### ISSUE THREAD

**Issue by imiskolee** [makepad/makepad#237]
It's exciting to see a nice Rust UI framework, and having seen the code in the examples, there are a few questions (or suggestions) I'd like to express:

1. whether ui code and logic code can be organized separately . For example, the following code structure

```bash
└── src
    ├── app.rs
    ├── components
    │ ├── my_stateful_component.rs
    │ ├── my_stateful_component.ui.rs
    │ └── my_stateless_component.ui.rs
    └── main.rs
```
The DSL is all located in *.ui.rs instead of mixing logic code with DSL code.

2. is the use of prefixes (namespaces) considered for enum type data, e.g.:

``rust
 flow : Flow.Down
```
Instead of.

``rust
flow:Down
``

**Comment by makepaddev** [comment]
I removed prefixes for Enums because it was bloating the DSL, i could reintroduce it as a 'noop' but for now its not in there. Separating DSL from UI code should be possible yea, there is no reason you cant split it.

**Comment by imiskolee** [comment]
> 

that prefix is very important for the user side to understand what we can use. and friendly with IDE auto-completed, I think.

**Comment by makepaddev** [comment]
Ill think about it

**Comment by tingfeng-key** [comment]
Are you closing it because it has already been implemented?
