### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by tingfeng-key** [makepad/makepad#243]
cmd:
```shell
cargo run -p cargo-makepad --release -- android run -p makepad-example-news-feed
```

log: 
```shell
Compiling APK & R.java files
Building APK
WARNING: Building debug build, this creates a very slow application. Use --release if this is not what you want.
Compile APK completed
Starting android application: makepad_example_news_feed.apk
--------- beginning of main
09-15 12:43:09.338 27476 27516 D Makepad : platform\src\os\linux\android\android.rs:399:17 - Android asset failed: cannot load dependency makepad/makepad_example_news_feed/resources/icon_add.svg
09-15 12:43:09.338 27476 27516 D Makepad : platform\src\os\linux\android\android.rs:399:17 - Android asset failed: cannot load dependency makepad/makepad_example_news_feed/resources/profile_1.jpg
09-15 12:43:09.338 27476 27516 D Makepad : platform\src\os\linux\android\android.rs:399:17 - Android asset failed: cannot load dependency makepad/makepad_example_news_feed/resources/icon_user.svg
09-15 12:43:09.338 27476 27516 D Makepad : platform\src\os\linux\android\android.rs:399:17 - Android asset failed: cannot load dependency makepad/makepad_example_news_feed/resources/icon_favorite.svg
09-15 12:43:09.366 27476 27516 D Makepad : widgets\src\image_cache.rs:207:21 - load_image_dep_by_path:  Resource not found makepad/makepad_example_news_feed/resources/profile_1.jpg cannot load dependency makepad/makepad_example_news_feed/resources/profile_1.jpg
09-15 12:43:09.492 27476 27516 D Makepad : widgets\src\image_cache.rs:207:21 - load_image_dep_by_path:  Resource not found makepad/makepad_example_news_feed/resources/profile_1.jpg cannot load dependency makepad/makepad_example_news_feed/resources/profile_1.jpg
09-15 12:43:09.494 27476 27516 D Makepad : widgets\src\image_cache.rs:207:21 - load_image_dep_by_path:  Resource not found makepad/makepad_example_news_feed/resources/profile_1.jpg cannot load dependency makepad/makepad_example_news_feed/resources/profile_1.jpg
09-15 12:43:09.495 27476 27516 D Makepad : widgets\src\image_cache.rs:207:21 - load_image_dep_by_path:  Resource not found makepad/makepad_example_news_feed/resources/profile_1.jpg cannot load dependency makepad/makepad_example_news_feed/resources/profile_1.jpg
09-15 12:43:09.497 27476 27516 D Makepad : widgets\src\image_cache.rs:207:21 - load_image_dep_by_path:  Resource not found makepad/makepad_example_news_feed/resources/neom-THlO6Mkf5uI-unsplash.jpg cannot load dependency makepad/makepad_example_news_feed/resources/neom-THlO6Mkf5uI-unsplash.jpg
09-15 12:43:09.497 27476 27516 D Makepad : widgets\src\image_cache.rs:207:21 - load_image_dep_by_path:  Resource not found makepad/makepad_example_news_feed/resources/profile_1.jpg cannot load dependency makepad/makepad_example_news_feed/resources/profile_1.jpg
09-15 12:43:09.498 27476 27516 D Makepad : widgets\src\image_cache.rs:207:21 - load_image_dep_by_path:  Resource not found makepad/makepad_example_news_feed/resources/profile_1.jpg cannot load dependency makepad/makepad_example_news_feed/resources/profile_1.jpg
```

**Comment by makepaddev** [comment]
We should verify android builds on windows, looks like it has a problem

**Comment by makepaddev** [comment]
It seems likely we have mixed up the \ in the windows paths

**Comment by tingfeng-key** [comment]
![image](https://github.com/makepad/makepad/assets/13976521/23b92d5d-c75c-466f-bd3d-39e9dae6002f)
After I made the changes, there was still a problem, but it won't keep outputting errors. It was always outputting before
![image](https://github.com/makepad/makepad/assets/13976521/0b5e5faf-2413-4b57-93d1-954a087eb80e)

**Comment by tingfeng-key** [comment]
Do I need to change `crate://` to `crate:\\`

**Comment by makepaddev** [comment]
No i fixed it already, please pull

**Comment by makepaddev** [comment]
It was just a bit of \\ vs / handling in the cargo makepad tool. be sure to reinstall it

**Comment by makepaddev** [comment]
Please note that makepad doesnt seem to want to run on the android simulator on windows, i have no fix for that for now. creating an EGL surface crashes the app.

**Comment by makepaddev** [comment]
Please undo any changes you made, shouldnt be necessary

**Comment by tingfeng-key** [comment]
It's normal now, thank you

**Comment by makepaddev** [comment]
Ok if found one more issue, see if it works now for you. It builds correctly here now, except for that i cant build for x86_64 simulator on windows for reasons unknown

**Comment by tingfeng-key** [comment]
Yes, it now displays images normally on my phone (previously there were no images), and I already know that it cannot run in the emulator because I am trying to run it on a virtual device in Android Studio.

**Comment by makepaddev** [comment]
I narrowed the simulator down to that zune-jpeg doesnt compile on x86_64 android

**Comment by makepaddev** [comment]
Ok i fixed the build on --abi=x86_64 you can now build for emulator as well

**Comment by tingfeng-key** [comment]
I don't know if I can raise another question here, let alone this one.

![image](https://github.com/makepad/makepad/assets/13976521/9e8f23ce-73f5-4342-b261-c258c06d835c)

When I click or swipe the mouse in the content area, it will fill incorrectly

**Comment by tingfeng-key** [comment]
> Ok i fixed the build on --abi=x86_64 you can now build for emulator as well

Do I need to set any parameters? Is it still possible to build the process normally?

**Comment by makepaddev** [comment]
This is about the android simulator, ignore the message otherwise.
Windows build is apparently still wonky. let me see

**Comment by tingfeng-key** [comment]
> cargo run -p cargo-makepad --release -- android run -p makepad-example-news-feed

I executed this command, but the result was still the same

```shell
Compiling APK & R.java files
Building APK
Compile APK completed
Got error: Process D:\learns\makepad\tools\cargo_makepad/./android_33_windows_x64\platform-tools/adb in dir "D:\\learns\\makepad" returned error exit code All files should be loaded. Notifying the device.
adb: failed to install D:\learns\makepad\target/makepad-android-apk/makepad-example-news-feed/apk\makepad_example_news_feed.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

**Comment by makepaddev** [comment]
run on x86 simulator:
cargo install ./tools/cargo_makepad
cargo makepad android --abi=all install-toolchain
cargo makepad android --abi=x86_64 run -p makepad-example-news-feed --release
lmk if this works, i tested here
Run on device aarch64 if connected
cargo makepad android --abi=aarch64 run -p makepad-example-news-feed --release

**Comment by makepaddev** [comment]
if you have another ABI for your device try the other ones
cargo makepad android --abi=armv7 run -p makepad-example-news-feed --release

**Comment by makepaddev** [comment]
Ok i fixed the window maximise issue on windows as well

**Comment by makepaddev** [comment]
You can git pull and let me know if it now works.

**Comment by makepaddev** [comment]
I also just fixed the ironfish example to work again on windows

**Comment by tingfeng-key** [comment]
> run on x86 simulator: cargo install ./tools/cargo_makepad cargo makepad android --abi=all install-toolchain cargo makepad android --abi=x86_64 run -p makepad-example-news-feed --release lmk if this works, i tested here Run on device aarch64 if connected cargo makepad android --abi=aarch64 run -p makepad-example-news-feed --release

build error log:

```shell
PS D:\learns\makepad> cargo makepad android --abi=x86_64 run -p makepad-example-news-feed --release
   Compiling makepad-zune-jpeg v0.3.17 (D:\learns\makepad\libs\zune-jpeg)
error: linking with `D:\learns\makepad\tools\cargo_makepad/./android_33_windows_x64\NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android33-clang.cmd` failed: exit code: 255
  |
  = note: "D:\\learns\\makepad\\tools\\cargo_makepad/./android_33_windows_x64\\NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android33-clang.cmd" "-Wl,--version-script=C:\\Users\\ld_100\\AppData\\Local\\Temp\\rustcrtKzxS\\list" "-Wl,--no-undefined-version" "-m64" "C:\\Users\\ld_100\\AppData\\Local\\Temp\\rustcrtKzxS\\symbols.o" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps\\makepad_zune_jpeg.makepad_zune_jpeg.ce22b20ba3cdcc92-cgu.0.rcgu.o" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps\\makepad_zune_jpeg.makepad_zune_jpeg.ce22b20ba3cdcc92-cgu.1.rcgu.o" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps\\makepad_zune_jpeg.makepad_zune_jpeg.ce22b20ba3cdcc92-cgu.2.rcgu.o" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps\\makepad_zune_jpeg.makepad_zune_jpeg.ce22b20ba3cdcc92-cgu.3.rcgu.o" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps\\makepad_zune_jpeg.makepad_zune_jpeg.ce22b20ba3cdcc92-cgu.4.rcgu.o" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps\\makepad_zune_jpeg.makepad_zune_jpeg.ce22b20ba3cdcc92-cgu.5.rcgu.o" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps\\makepad_zune_jpeg.makepad_zune_jpeg.ce22b20ba3cdcc92-cgu.6.rcgu.o" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps\\makepad_zune_jpeg.x5manu5ofg7rd6j.rcgu.o" "-Wl,--as-needed" "-L" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps" "-L" "D:\\learns\\makepad\\target\\release\\deps" "-L" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib" "-Wl,-Bstatic" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps\\libmakepad_zune_core-ff64601304212465.rlib" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps\\libbitflags-f2a8d4f47bdb6a2d.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libstd-0315d03472a15c98.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libpanic_unwind-f4f5bee12cc78625.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libobject-6b094c4b15f5dc7d.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libmemchr-11e54792af978b4c.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libaddr2line-0349d5db54384767.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libgimli-07fec16210611fc4.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\librustc_demangle-c252a427ea0a996f.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libstd_detect-2d4520418173e337.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libhashbrown-596ac8c2ae9133e2.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\librustc_std_workspace_alloc-92581d78a0b0f78c.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libminiz_oxide-d2227b0815bbf46e.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libadler-1627fdebb90c3972.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libunwind-8ddf65c566e04234.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libcfg_if-a64dec7b3a29bbe7.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\liblibc-876580d2001d7e95.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\liballoc-1f094d0794305a83.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\librustc_std_workspace_core-8a32cb70d75c1b93.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libcore-e8de608454e6b8f1.rlib" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib\\libcompiler_builtins-a0fed207e40bfb36.rlib" "-Wl,-Bdynamic" "-ldl" "-llog" "-lunwind" "-ldl" "-lm" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "C:\\Users\\ld_100\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-linux-android\\lib" "-o" "D:\\learns\\makepad\\target\\x86_64-linux-android\\release\\deps\\libmakepad_zune_jpeg.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs"
  = note: Non-UTF-8 output: \xb4\xcb\xca\xb1\xb2\xbb\xd3\xa6\xd3\xd0 --version-script=C:\\Users\\ld_100\\AppData\\Local\\Temp\\rustcrtKzxS\\list\"\"\xa1\xa3\r\n

error: could not compile `makepad-zune-jpeg` (lib) due to previous error
Got error: Process rustup in dir "D:\\learns\\makepad" returned error exit code
```

**Comment by makepaddev** [comment]
Looks like you might have non utf8 characters in your paths.. somehow

**Comment by makepaddev** [comment]
This works here on my PC

**Comment by tingfeng-key** [comment]
> You can git pull and let me know if it now works.

There is no problem running maximization after pull

**Comment by makepaddev** [comment]
Yea i also want the android builds to work

**Comment by makepaddev** [comment]
Let me try something else

**Comment by tingfeng-key** [comment]
> This works here on my PC

I am now rebuilding it on x86_ 64 is running normally, I'm not sure if you processed it after dealing with the image issue, because I built x86_ 64 failed using the pull code for image repair

**Comment by makepaddev** [comment]
Ok so it works now?

**Comment by tingfeng-key** [comment]
> if you have another ABI for your device try the other ones cargo makepad android --abi=armv7 run -p makepad-example-news-feed --release

I'm not sure if it's possible to test aarch64 and armv7 on my phone. I'll give it a try

**Comment by makepaddev** [comment]
Your phone will be either aarch64 or armv7

**Comment by tingfeng-key** [comment]
> Ok so it works now?

Yes, it can now run normally on virtual devices in Android Studio

**Comment by makepaddev** [comment]
You can specify multiple ABI's for the apk, but this slows down the build:
cargo makepad android --abi=aarch64,armv7 run -p makepad-example-news-feed --release

**Comment by tingfeng-key** [comment]
> Your phone will be either aarch64 or armv7

My phone is arm64-v8a, I'm sorry, we couldn't test the other two build methods

**Comment by tingfeng-key** [comment]
> You can specify multiple ABI's for the apk, but this slows down the build: cargo makepad android --abi=aarch64,armv7 run -p makepad-example-news-feed --release

Okay, I'll give it a try

**Comment by makepaddev** [comment]
we know armv7 works so that should be ok. So yea all good then.

**Comment by tingfeng-key** [comment]
Additionally, I have a question. Based on my test results, regardless of whether the resource issue is significant (I may have forgotten whether it includes large resource files), the size of the constructed APK is very large (30M). I am not sure why this is the case

**Comment by makepaddev** [comment]
Which example, and how many ABI's did you pass in, and did you use --release?

**Comment by makepaddev** [comment]
We can set the build to size optimized as well.

**Comment by tingfeng-key** [comment]
> Which example, and how many ABI's did you pass in, and did you use --release?

I tested the news feed and the result was that the 30M size was due to not using - release. After using - release, the size was 10M and abi was aarch64

**Comment by makepaddev** [comment]
If you edit the root Cargo.toml file in our repo and you remove the comment before these items: I get a 2.5mb dll per ABI.
opt-level = 'z'     # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
panic = 'abort'     # Abort on panic
strip = true

**Comment by tingfeng-key** [comment]
> > Which example, and how many ABI's did you pass in, and did you use --release?
> 
> I tested the news feed and the result was that the 30M size was due to not using - release. After using - release, the size was 10M and abi was aarch64

I still feel that this size is quite large. I know this example only has one page and not many resources (42K). I guess the font file (ttf) is included in it. I don't know if this is the case

**Comment by makepaddev** [comment]
If you do that the APK is about 9mb with one ABI. However the reason its so big is because there is a MASSIVE 15mb (7mb compressed) international font in the build

**Comment by makepaddev** [comment]
So the size build up (when using size optimised build, compressed) is:
+- 1mb binary per ABI
+- 7,5mb font
+- 500kb other images / things

**Comment by makepaddev** [comment]
1mb compressed per ABI is not that large imho, Rust is not very size optimised. The big chunk is the fonts.

**Comment by makepaddev** [comment]
We'll provide ways to more easily configure the fonts you ship and also to create size optimised builds. You can get back down to a 2mb apk for a single ABI.

**Comment by tingfeng-key** [comment]
Yes, I'm sure it's a font size issue. Is it possible to use the system's font file without including the font file (i.e. not using a separate font file)?


> If you edit the root Cargo.toml file in our repo and you remove the comment before these items: I get a 2.5mb dll per ABI. opt-level = 'z' # Optimize for size lto = true # Enable link-time optimization codegen-units = 1 # Reduce number of codegen units to increase optimizations panic = 'abort' # Abort on panic strip = true

**Comment by tingfeng-key** [comment]
> We'll provide ways to more easily configure the fonts you ship and also to create size optimised builds. You can get back down to a 2mb apk for a single ABI.

Is it a way of using system fonts?

**Comment by makepaddev** [comment]
We might also be able to load font files already installed on the device and shrink more, i have not investigated. However that 1mb binary per ABI is kindof irreducible that is our lower limit

**Comment by makepaddev** [comment]
System fonts might be usable, i have to investigate.

**Comment by tingfeng-key** [comment]
> System fonts might be usable, i have to investigate.

Okay, I'm looking forward to it

**Comment by makepaddev** [comment]
Yea we're working on more optimised packaging tooling as well. It's all very rudimentary at the moment. It's not really in any way production ready, we dont even have icon support yet.

**Comment by makepaddev** [comment]
You should remove those options again from Cargo.toml if you are going to be iterating the build, it is much slower to compile than without the size optimisations

**Comment by makepaddev** [comment]
Btw if you track branch 'rik' i dont have to push to master all the time.

**Comment by makepaddev** [comment]
I added a --profile=small option you can do instead of the --release, that will use the size optimised build. The rest is the font, but we'll fix that.

**Comment by tingfeng-key** [comment]
Okay, I would like to raise another question about internationalization languages. In the SDxl example, Chinese can be written in the search input box, but the following two input boxes do not support Chinese input. I then compared the code but did not find any relevant or special attributes

**Comment by tingfeng-key** [comment]
Okay, thank you for informing us

**Comment by makepaddev** [comment]
Hmm the chinese input thing is strange. I dont know why tbh, will have to debug it

**Comment by tingfeng-key** [comment]
Okay, thank you for your efforts and response. This is a great and interesting library, and I am very optimistic about it. I look forward to further improvement

**Comment by makepaddev** [comment]
hmm --profile=small might have a path issue, sec

**Comment by makepaddev** [comment]
Yea i need to parse it and include it as binary path for the packagers. one moment

**Comment by makepaddev** [comment]
Ok i fixed up profile parsing in the cargo build tool, on rik branch

**Comment by makepaddev** [comment]
Now you can pass in --release or --profile=small

**Comment by tingfeng-key** [comment]
Okay, thank you very much. I will try it out later
