### ISSUE TITLE
Createdxgifactory2 Could not be Located on win7！！

### ISSUE THREAD

**Issue by zhoujun681** [makepad/makepad#290]
Win7 cannot run！！

**Comment by makepaddev** [comment]
Sorry i have too many features i use from newer windows systems to go back to windows 7. I can try tho but its going to break Dx11 shaders, DPI support, all sorts of things. I decided against supporting win7 for now.

**Comment by makepaddev** [comment]
It shouldn't be technically impossible, but it'l cruft up the windows code all over the place.

**Comment by zhoujun681** [comment]
understand that!
