### ISSUE TITLE
News feed images not showing on android

### ISSUE THREAD

**Issue by yulnr** [makepad/makepad#349]
Images are not showing for the news feed example app on android. Works fine on linux and mac. 

Probably related: there was this mention on text not working on the same app which I haven't managed to replicate:
_@univerz in https://github.com/makepad/makepad/issues/346#issuecomment-1864605228_

**Comment by univerz** [comment]
> I haven't managed to replicate: _@univerz in [#346 (comment)](https://github.com/makepad/makepad/pull/346#issuecomment-1864605228)_

maybe it's the latest android update (pixel 7 pro) - i noticed that my older app i have on my phone stopped working completely (starts, but shows dark grey screen)

**Comment by guofoo** [comment]
Are you able to reproduce this problem?

I just tried installing the news feed example on my Pixel 7 Pro (upgraded to Android 14 a few weeks ago) and is able to see the images with no problem.

**Comment by univerz** [comment]
cleaned rustup, cloned fresh makepad repo, rik branch, no success: 

![Screenshot_20240105-174355](https://github.com/makepad/makepad/assets/1024741/c96d8ef2-087c-4650-82ed-5f6b01bd05a7)

**Comment by univerz** [comment]
last missing cleanup - removed all makepad apps from phone & text is working (no photos):
![Screenshot_20240105-180712](https://github.com/makepad/makepad/assets/1024741/e95c79c6-7236-4fc9-9ef3-f5b3cc6727e1)

**Comment by yulnr** [comment]
@univerz thanks for sharing! I'm assuming you're not seeing any errors in the terminal right?
Can you by chance check for logs on something like logcat from Android Studio? I don't have a Pixel 7 and can't replicate it through emulator. (Also testing with latest android on other devices)

Edit: nvm android is not logging to adb on `rik` branch. I locally have a hack for logging to adb on android, perhaps we can fix that up so you can debug properly. Will keep you updated.

**Comment by yulnr** [comment]
Update: I don't have a solution for this one yet as I'm working on other rendering issues. However I can confirm that this is a problem with missing assets when the app is within the makepad repo. `Dependency not loaded - load_image_dep_by_path:  Resource not found` error when attempting to load the images into memory.

I believe this is happening inconsistently as some people can't manage to replicate it.

**Comment by univerz** [comment]
i saw the fixed `log` and wanted to debug this, but the images are already working :man_shrugging:

**Comment by yulnr** [comment]
> i saw the fixed `log` and wanted to debug this, but the images are already working 🤷‍♂️

Right! that issue got fixed today by https://github.com/makepad/makepad/commit/7d1ecf84ed8ec705be5b1a2dec9b870d2571a23a
There was problem loading dependencies on apps inside the makepad repo.
Since you confirm that it's working for you as well I'll close this.
