### ISSUE TITLE
Unconventional arrow-key behavior in selections when not holding shift

### ISSUE THREAD

**Issue by jceipek** [makepad/makepad#35]
By convention, pressing the left/right arrow key when there is an active text selection should collapse the selection and move the caret to the side of the selection range in the direction of the pressed arrow. I've observed this across macOS input controls, including code editors, and in IMGUI. I haven't had a chance to try on Windows/Linux systems, but I expect the behavior there will be the same.

In makepad, pressing the left/right arrow key currently collapses the selection but additionally moves the caret based on the position of the head of the selection (h):

```
1) Given:
so|me te|xt
  h     t

-> Left Arrow ->

Result:
s|ome text
 h
 t

2) Given:
so|me te|xt
  h     t

-> Right Arrow ->

Result:
som|e text
   h
   t
```

Compare to the following expected behavior:
```
1) Given:
so|me te|xt
  h     t

-> Left Arrow ->

Result:
so|me text
  h
  t

2) Given:
so|me te|xt
  h     t

-> Right Arrow ->

Result:
some te|xt
       h
       t
```

This is a minor defect that should be trivial to fix (probably just tweaks to `move_left` and `move_right` in `textcursor.rs`), but it is super annoying when selecting text in a code editor doesn't work "properly."

On a related note, I wonder if anyone has documented text editing conventions/differences between editors/OSes and which text editor first introduced the conventions of arrow key + shift + other modifier behavior. I've spent some time looking online but haven't found anything.

**Comment by makepaddev** [comment]
Ah yes this was on my todo still, i'll fix it.

**Comment by makepaddev** [comment]
Its now fixed in master.
