### ISSUE TITLE
Multiple-cursor editing: glitches and hanging

### ISSUE THREAD

**Issue by nyanpasu64** [makepad/makepad#4]
## Freeze bug

Click on one spot. Ctrl-click on the same or another character. Ctrl+A and backspace.

## Glitchy multiple selections

Click on one spot. Ctrl-click on the same spot. Then try typing (characters will appear left AND right of the cursor) or pressing backspace.

Reproduction steps:

- Open https://makepad.github.io/makepad/
- Clear the document
- Type asdf
    - two asdf appear, cursor is between them
- press backspace
    - asd cursor asd (both f disappear)

## Browser

https://makepad.github.io/makepad/
Firefox 67.0b17 (64-bit), Ubuntu 18.04

**Comment by makepaddev** [comment]
Thanks for reporting, fixing!

**Comment by makepaddev** [comment]
I did my 'actual last char in the buffer' handling sloppy. Going through it.

**Comment by makepaddev** [comment]
All issues resolved!
https://makepad.github.io/makepad/
