### ISSUE TITLE
Bezier curve not rendered correctly

### ISSUE THREAD

**Issue by mneilly** [makepad/makepad#418]
The following SVG is a modified version of the Font Awesome _floppy-disk-regular_ icon. What is supposed to be a circle in the middle is drawn with an arc in the original icon but has been replaced with a curve here (the last curve at the end of the path). This renders correctly in Edge and the Rust Rover image viewer but is rendered incorrectly by makepad.

![image](https://github.com/makepad/makepad/assets/5897087/3e5f58b1-9660-4de2-ab7c-7420995f1b6e)

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
  <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
  <path d="
  m 48,96
  v 320
  c 0,8.8 7.2,16 16,16
  h 320
  c 8.8,0 16,-7.2 16,-16
  V 170.5
  c 0,-4.2 -1.7,-8.3 -4.7,-11.3 l 33.9,-33.9
  c 12,12 18.7,28.3 18.7,45.3
  V 416 c 0,35.3 -28.7,64 -64,64
  H 64 C 28.7,480 0,451.3 0,416
  V 96 C 0,60.7 28.7,32 64,32
  h 245.5 c 17,0 33.3,6.7 45.3,18.7
  l 74.5,74.5 -33.9,33.9
  L 320.8,84.7 320,83.9
  V 184
  c 0,13.3 -10.7,24 -24,24
  H 104
  C 90.7,208 80,197.3 80,184
  V 80 H 64
  c -8.8,0 -16,7.2 -16,16
  z
  m 80,-16
  v 80
  H 272
  V 80
  Z
  m 30,240
  c 0,-35.34625 30.65378,-63.99997 66,-63.99997 35.34622,0 66,28.65372 66,63.99997 0,35.34625 -30.65378,63.99997 -66,63.99997 -35.34622,0 -66,-28.65372 -66,-63.99997
  z
"/>
</svg>
```

The original arc was `a64 64 0 1 1 128 0 64 64 0 1 1 -128 0`.

**Comment by StijnKuipers** [comment]
<img width="481" alt="image" src="https://github.com/makepad/makepad/assets/205945/82c5de33-c0f3-4079-9a52-154a3afc9a03">

**Comment by mneilly** [comment]
Sorry, don't intend to sound rude but since this was closed without comment I'm left wondering if this was a 'works for me' or 'it has been fixed'. Can you provide the git hash that worked to generate your image? I've tried the latest rik and master branches and still see the issue.

**Comment by StijnKuipers** [comment]
Whoops! My excuses!

[cfc79dedeabec19faf17bb47d8e1c7d38c2cf62b ](https://github.com/makepad/makepad/commit/cfc79dedeabec19faf17bb47d8e1c7d38c2cf62b)

This is the fix that made the dot go back to center. The Z command did not reset the origin position to the first in the drawing. 

To test this I made a standalone testapp with 1 <Icon> element and the source you pasted above saved as file.svg

Can you show me how you are using this icon?

**Comment by mneilly** [comment]
Thanks! That helped me realize my own mistake. I pulled from upstream to get the latest master but I apparently I pulled from my own fork to update rik. Sigh. I do see the change now and it does work for me. Thanks!!

```rust
ImageEditor = {{ImageEditor}} {
    <View> {
        flow: Down, width: Fill, height: Fill
        controls = <View> {
            flow: Right, width: Fill, height: Fit
            load_button = <Button> {
                draw_icon: {
                    svg_file: dep
                    ("crate://self/resources/icons/svg/file-image-regular.svg")
                    fn get_color(self) -> vec4 { return (#b197fc) }
                }
                icon_walk: { width: 28.0, height: 32.0 },
            }
            save_button = <Button> {
                draw_icon: {
                    svg_file: dep
                    ("crate://self/resources/icons/svg/floppy-disk-regular-noarc.svg")
                    fn get_color(self) -> vec4 { return (#ffd33b) }
                }
                icon_walk: { width: 28.0, height: 32.0 },
            }
            crop_button = <Button> {
                draw_icon: {
                    svg_file: dep
                    ("crate://self/resources/icons/svg/crop-simple-solid.svg")
                    fn get_color(self) -> vec4 { return (#74c0fc) }
                }
                icon_walk: { width: 28.0, height: 32.0 },
            }
        }
        main_view = <View> {
            ...
        }
    }
}
```
