### ISSUE TITLE
`TextInput` functional issues in `rik` branch

### ISSUE THREAD

**Issue by noxware** [makepad/makepad#518]
Apart from the warnings stuff, here is a functional report of stuff that seems to be currently broken with text inputs in the `rik` branch (as of 1a35f8609):

For a simple text input (doing nothing special with it, just putting it in the DSL):
- Keyboard interactions and Cmd+A seems to work fine.
- Mouse interactions are broken:
	- Text selection by clicking and dragging requires you to "go up" with the mouse to do something.
	- Double clicking fast to select a word only selects the last world.
		- But if you click too fast many times it does nothing.
		- You can't select the whole text by clicking fast multiple times.
	- You can't move the cursor by clicking. Clicking into the text input will send the cursor to the end always (assuming you could test this by previously moving to the left with the keyboard).
- Minimal example code: https://github.com/noxware/makepad/tree/text-input-debug/examples/text_input_simple (see `ui.rs`).
- Most text inputs in moxin are like this, so fixing the example should fix this for moxin.

A text input whose value is set before drawing it (a possible way to bind a value to it):
- Almost doesn't work at all.
- You can't move the cursor from the start position, so you can only insert characters at the beginning. 
- You can't do anything with the mouse.
- You can't do anything with the keyboard (no text selection, no cursor movement, nothing except inserting characters at start).
- Minimal example code: https://github.com/noxware/makepad/tree/text-input-debug/examples/text_input_controlled (see `ui.rs`).
- The chat inference parameters panel in moxin is like this, so fixing the provided example should fix this for moxin.

I made simple examples so we don't need to test against moxin but we are experiencing this issues in @jmbejar branch that tries to use the `rik` branch in moxin https://github.com/moxin-org/moxin/pull/221.

> There is one exception case in moxin that seems to work almost fine, the edit message text input. The only thing broken there is that doing multiple clicks doesn't select the whole text and clicking too fast does nothing (similar to the first case), but clicking to change the cursor position works. I don't know why this works a bit better.

https://github.com/user-attachments/assets/8bcd5161-a892-4f17-b264-b7bbf4fba7d4

https://github.com/user-attachments/assets/7b402c54-ca87-4750-a9c9-b2a435740ec5

**Comment by makepaddev** [comment]
All issues should be resolved now in rik branch, please verify. Also adding cursorblinking still.

**Comment by noxware** [comment]
Testing against 87ca3ab6c9e708afdc2a9eaa7c86bd8ad5a93605, all problems mentioned by this issue seem to be resolved ✅
