### ISSUE TITLE
Native panicked in MacOS

### ISSUE THREAD

**Issue by snadon** [makepad/makepad#6]
When I run `./watch_native.sh`, the window appears in the bottom left corner and barely visible (I'm using two monitors). It crashes every time I try to maximize or to resize the window.

```
[Running 'cargo build --release && cargo run --release']
    Finished release [optimized] target(s) in 0.36s
    Finished release [optimized] target(s) in 0.10s
     Running `target/release/makepad`
get_uniform_offset blink called on invalid prop
get_instance_offset x called on invalid prop
get_instance_offset y called on invalid prop
get_instance_offset font_geom called on invalid prop
get_instance_offset font_size called on invalid prop
get_instance_offset char_offset called on invalid prop
get_uniform_offset blink called on invalid prop
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/slice/mod.rs:2539:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic_bounds_check
   9: editor::rusteditor::RustEditor::draw_rust_editor
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  11: render::cx::Cx::call_event_handler
  12: render::cx::Cx::call_draw_event
  13: render::cx_mtl::<impl render::cx::Cx>::event_loop
  14: makepad::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start_internal
  19: main
[Finished running. Exit status: 101]
```

It does that with either rust stable or nightly. `./server_webgl.sh` works.

Keep up the good work I'm so impressed by this project 👍

**Comment by makepaddev** [comment]
I have the application hard locked to start up on my second monitor, also i'm fixing so many things right now i don't even know if its temporary bug. It'l be more stable in a few days. Btw if you want to be more helpful try ./watch_debug.sh that will actually give a full stacktrace.

**Comment by makepaddev** [comment]
So i'm dogfooding this thing rn, so try to do this 
git clone git@github.com:/makepad/makepad edit_repo 
in the root (im editing the thing with itself in native)

**Comment by makepaddev** [comment]
Yeah that fixes it. Sorry i keep the wasm version working always but the native one is moving fast now since i'm dogfooding it on itself.

**Comment by makepaddev** [comment]
Alright please pull, run ./run_first_init.sh to create the sub editable repo,
then ./build_release.sh and you should be up and running

**Comment by snadon** [comment]
Up and running! Thank you!

**Comment by makepaddev** [comment]
Np, yea its all like barely standing but im forcing myself to write itself in itself now, i'll make the startup flow a bit better now maybe a commandline arg to give it a root dir, stuff like that.

**Comment by makepaddev** [comment]
On the upside, you should be able to see it work :) including rust compiler errors

**Comment by snadon** [comment]
Yeah it totally works. This is so exciting.
