### ISSUE TITLE
Text window doesn't scroll sideways with touchpad on Ubuntu

### ISSUE THREAD

**Issue by ChrisMacNaughton** [makepad/makepad#73]

**Comment by makepaddev** [comment]
Investigating.

**Comment by makepaddev** [comment]
Please check out the dev branch and try it. Is the scroll direction of both (vertical) and (horizontal) now what you expect? or do i need to invert one.

**Comment by makepaddev** [comment]
Its now the same as firefox, so that should be right. Closing.

**Comment by ChrisMacNaughton** [comment]
Yup, touchpad scrolls correctly now :)
