### ISSUE TITLE
Content offset when page is zoomed (Safari)

### ISSUE THREAD

**Issue by swiftcoder** [makepad/makepad#8]
If I zoom the page using the trackpad on Safari, makepad ends up correctly sized for the zoom level, but it is offset from the actual browser window:

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/4706210/59479169-81a0c800-8e4b-11e9-81cf-ba54fc2b7196.png">

Does not occur on Chrome or Firefox (trackpad pinch doesn't zoom the page on either). Does not occur when zooming with ⌘+ keyboard shortcut in any browser.

**Comment by makepaddev** [comment]
I googled it but it doesn't appear possible to block this behavior. However i've forced the window scroll to be 0,0 so atleast the application still works. But it will get a bit blurry.
