### ISSUE TITLE
long files fail to display

### ISSUE THREAD

**Issue by ghost** [makepad/makepad#80]
i.e. https://github.com/makepad/makepad/blob/master/render/bind/x11-sys/src/bindings.rs
fails to even show text:
![PrtScr--2020-02-08--234637-fs8](https://user-images.githubusercontent.com/59403389/74093084-73d03f00-4acd-11ea-9818-31df05b5d7f2.png)

**Comment by makepaddev** [comment]
I didn't know it exceptioned but the editor is being designed/crafted for live value editing and code folding. I can't make this work with O(1) file editing its O(lines). Since there are plenty O(1) editors and makepads entire purpose is with these special features, i'll think about what to do with this problem. Maybe a nice error, eventually maybe an O(1) edit mode.

**Comment by arekbal** [comment]
@makepaddev 
If I were to suggest something simple, that might help in the future - connect your frontend reporting to some backend logger.

Sadly, some scripts will unevitably be long as F#. Pun intended. :) 
Approaching this situation in efficient manner, is a must for any editor. 

Then, there is an issue of trully big files (GBs of CSV) which could be ignored, but still you will need to have a plan for that, like not displaying the file and saying to user that it is too big to open and present in reasonable time or - like you mentioned - just open it, in "non-foldable, non-formatted" seek mode and let user know why you did so.

**Comment by makepaddev** [comment]
I can do a multi-GB file editor, its just a quite different piece of tech. I'll put 'make proper error' on the todo list.

**Comment by arekbal** [comment]
But how many lines of code currently is a right amount?

**Comment by makepaddev** [comment]
I just profiled the web version on my fast machine, it starts to become less nice at 10k+. So thats still quite a large range of utility.

**Comment by makepaddev** [comment]
Native is twice the speed, so it really depends on your env and PC specs what the limit is.

**Comment by makepaddev** [comment]
The reason why its an O(lines) editor will become apparent when im doing live value editors. They run via the autoformatter on the 'entire' tokenstream. Its technically possible to make this scale better but it will make certain features much harder to do (like the folding, things like comment blocks).

**Comment by makepaddev** [comment]
Essentially the story is, if i can't show the value of what im trying to achieve with this simpler model, and this constraint, going beyond 10k+ lines albeit useful for some isn't going to make the difference.

**Comment by makepaddev** [comment]
I think the right answer will be that i'll add a 'big file editor' at some point in the future that doesnt have folding, and limited syntax highlighting.
