### ISSUE TITLE
Error when starting makepad from another folder

### ISSUE THREAD

**Issue by Eragonfr** [makepad/makepad#81]
When i start Makepad from any other folder than the root of the repo i get this error.  
```
Error loading font resources/Ubuntu-R.ttf 
Error loading font resources/LiberationMono-Regular.ttf 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Is it possible to load that files from a relative path to the binary ?

**Comment by makepaddev** [comment]
Right now we don't have a fix for that, but we are working on deploying via cargo, which will solve this problem. For now patch up some paths, but it'l be fixed in the next release.

**Comment by Eragonfr** [comment]
Where is defined these path ? In which file ?

**Comment by makepaddev** [comment]
Right now in widget/src/widgetstyle.rs you see 2 font paths. Try making those absolute.

**Comment by rsaccon** [comment]
I got around this current problem by adding a `resources` folder containing the font files a the root of  my project.

**Comment by makepaddev** [comment]
That works too. We'll fix this nicely soon with makepad released on crates.io.

**Comment by teohhanhui** [comment]
Just want to note that deploying the `resources` directory alongside the binary is not a solution, as it goes against (most?) packaging guidelines.

Ran into this issue while creating an [AUR package](https://aur.archlinux.org/packages/makepad-git). For now I'll patch.

**Comment by makepaddev** [comment]
It's not nice no, but i need some place to get the font files. So there will need to be a resources/fonts directory somewhere.

**Comment by Eragonfr** [comment]
Is it possible to change the font to use the system fonts ? On linux it's something like `/usr/share/fonts/…`  using a patch file you can temporary change the code to use a system folder.
I'v searched where are the references to this folder inside the code, if i remember this folder is referenced only 2 or three times.

Also it can be a great idea to set the font/resources folder inside a str or a String somewhere in the code, so it's simple to change the location of this folder.

EDIT: misconstruction of my comment, sorry

**Comment by makepaddev** [comment]
Yea thats a possibility. I'll review it next iteration when we push to crates.io, its been on the todo list.

**Comment by teohhanhui** [comment]
> there will need to be a resources/fonts directory somewhere.

Sure, but it needs to respect the system directories. On Arch Linux this would be `/usr/share/makepad`: https://wiki.archlinux.org/index.php/Arch_package_guidelines#Directories

There's https://crates.io/crates/dirs which can help with finding the right directories.

**Comment by makepaddev** [comment]
Also relying on system fonts is a road to hell though. Its going to be different on every platform, or not work at all.

**Comment by makepaddev** [comment]
Thanks that seems useful, i'll use that when we fix that bit up.
