### ISSUE TITLE
UI toolkit - again

### ISSUE THREAD

**Issue by arekbal** [makepad/makepad#83]
First of all, very good job guys, keep it going.

I am slowly, but surely prepping for next project and then - in the meantime - another one, and another one are in plans...
Technologically nothing fancy, just another business idea realized with technology in mind. 
I was planning initially to go FE react, BE dotnet.

As I already did some experiments in Rust, I know where Rust becomes a bit of a hassle and feel that our use cases are easy enough to move forward with Rust for BE.
Story of actix-web and diesel are good enough, so we (all of us) could use Rust as backend for the most-of-the-web - I believe.

What people currently want - me included - is good frontend framework in Rust. 
I did some research on this, wasm story for now is that webgl way could be the fastest but is also the hardest (capt. obv). Another approach is to go with dual engines (async DOM over some abstract layer to mitigate performance issues of wasm to DOM calls). The second approach is easier and would allow us to use some of existing tools and frameworks. Yew went that route, but made some fundamental errors in design along the way and now they try to dig their way out of a small? hole before 1.0.0.

You guys are currently frontrunners of webgl UI story, that is just a fact. If I currently were to invest fully into bleeding edge, you guys, would be the target.

I understand that problematic part of having a technology that is not a 'product' itself and how it leads to true problem - money for development of technology and no effective strategy to scale-up from just technology. I understand your focus points. 

On the other hand... if you were to "release" some UI baseline - foundation of sorts - upon which we could build our own UI toolkit/s... there is a value in it for you as well. Even with your 'makepad' project, you could use community created widgets for your development. Something as technologically basic as data grid is a lot of development work, and the list goes on: date time pickers, forms, toasts, combo-boxes, menus, data-binding systems, styling, automation and so on... 
I think the project is at this place - this approach is possible and we all could build upon your work if proper Cornerstones were placed.

PS. Obviously it is nicer to have eveything in single package like Material UI, but "we" as Rust frontend developers are more on the stage of "JQuery first time going mainstream". I think history proved it is a "natural" way of improving these technologies. Aaand having competition around it in UI widgets -> toolkits field proved useful in general.

**Comment by makepaddev** [comment]
Hi, yeah the 'there is no money in building a UI kit alone' part is where we are having a bit of trouble. We are hard at work building the makepad live developer env, to show the value we are trying to create. Hopefully that will be enough on its own to be a business. And part of what you can build with that dev env will definitely also be UI. However 'doing UI properly' is a bit of a different ballgame for now, as you said it needs a 'massive list of complex widgets that are a lot of work' and also UI design tooling. We're considering the UI angle but only after we get our our 'next gen tool' out in the next 6mo. In terms of the time investment keeping our opensource-efforts on this UI stack to a minimum for now will be the only way we can get enough done. Same with API changes, we have a change of shader syntax (rust->GLSL) coming in, these kinds of changes suck with a large OSS community making things. It will happen, just not yet.
