### ISSUE TITLE
git pull and build failed

### ISSUE THREAD

**Issue by lizhuoqi** [makepad/makepad#88]
`> cargo run -p makepad --releasecar`, and terminal info.
<img width="1105" alt="截屏2020-08-03 17 48 08" src="https://user-images.githubusercontent.com/22311295/89169980-99885d80-d5b1-11ea-9655-0f447f1bee88.png">

`rustup show`
<img width="374" alt="截屏2020-08-03 17 59 04" src="https://user-images.githubusercontent.com/22311295/89170981-11a35300-d5b3-11ea-9612-26712bb2d1bd.png">

`git commit`
<img width="923" alt="Carbonize 2020-08-03 at 18 03 06" src="https://user-images.githubusercontent.com/22311295/89171394-b0c84a80-d5b3-11ea-91c6-e07627bd5faf.png">

**Comment by makepaddev** [comment]
Did you try 'rm *.ron' in the makepad directory

**Comment by makepaddev** [comment]
we don't have upgrade handling for those things yet.

**Comment by makepaddev** [comment]
Hold up, someone accidentally pushed to master. Resolving.

**Comment by makepaddev** [comment]
This is the commit you need 2a77e73f0b975cfec29e68fc9c2d8e0ee4a70785
We're pointing master back to this commit. Thanks for the report!
