### ISSUE TITLE
I found that the color! macro in examples no longer exists

### ISSUE THREAD

**Issue by Cupnfish** [makepad/makepad#91]
I found this function under this path : render\src\colors\color
But direct replacement cannot compile:
```
expected struct `makepad_shader_compiler::colors::Color`, found struct `makepad_render::colors::Color`
```
My doubt is why two different Color structures are needed...

**Comment by makepaddev** [comment]
Ah yes, we need to update those to pick!() macro.

**Comment by makepaddev** [comment]
I'll push an update to master shortly

**Comment by makepaddev** [comment]
Done, let me know if it works for you now.
